import type { SubjectMeta } from "../../data/types";

export const meta: SubjectMeta = {
  id: "espain",
  lastmod: "2026-07-28",
  name: "Nacionalidad Española",
  degree: "¿Eres español/a?",
  course: 1,
  courseCode: "ESPAÑA",
  icon: "🇪🇸",
  contentPolicy: "authorized-exams",
  topics: [
    {
      key: "tarea-1",
      label: "Tarea 1: Gobierno e instituciones",
      icon: "🏛️",
      color: "blue",
    },
    {
      key: "tarea-2",
      label: "Tarea 2: Nacionalidad y ciudadanía",
      icon: "⚖️",
      color: "indigo",
    },
    {
      key: "tarea-3",
      label: "Tarea 3: Territorio y geografía",
      icon: "🗺️",
      color: "green",
    },
    {
      key: "tarea-4",
      label: "Tarea 4: Cultura e historia",
      icon: "🎨",
      color: "purple",
    },
    {
      key: "tarea-5",
      label: "Tarea 5: Vida cotidiana y trámites",
      icon: "🧾",
      color: "orange",
    },
  ],
  exams: [
    {
      year: "modelo-ccse",
      title: "Modelo CCSE",
      passPoints: 15,
      totalPoints: 25,
      durationMinutes: 45,
      hasPdf: false,
    },
    {
      year: "test1",
      title: "Test 1",
      passPoints: 15,
      totalPoints: 25,
      durationMinutes: 45,
      hasPdf: false,
    },
    {
      year: "test2",
      title: "Test 2",
      passPoints: 15,
      totalPoints: 25,
      durationMinutes: 45,
      hasPdf: false,
    },
    {
      year: "test3",
      title: "Test 3",
      passPoints: 15,
      totalPoints: 25,
      durationMinutes: 45,
      hasPdf: false,
    },
    {
      year: "test4",
      title: "Test 4",
      passPoints: 15,
      totalPoints: 25,
      durationMinutes: 45,
      hasPdf: false,
    },
    {
      year: "test5",
      title: "Test 5",
      passPoints: 15,
      totalPoints: 25,
      durationMinutes: 45,
      hasPdf: false,
    },
    {
      year: "test6",
      title: "Test 6",
      passPoints: 15,
      totalPoints: 25,
      durationMinutes: 45,
      hasPdf: false,
    },
    {
      year: "test7",
      title: "Test 7",
      passPoints: 15,
      totalPoints: 25,
      durationMinutes: 45,
      hasPdf: false,
    },
    {
      year: "test8",
      title: "Test 8",
      passPoints: 15,
      totalPoints: 25,
      durationMinutes: 45,
      hasPdf: false,
    },
    {
      year: "test9",
      title: "Test 9",
      passPoints: 15,
      totalPoints: 25,
      durationMinutes: 45,
      hasPdf: false,
    },
    {
      year: "test10",
      title: "Test 10",
      passPoints: 15,
      totalPoints: 25,
      durationMinutes: 45,
      hasPdf: false,
    },
    {
      year: "test11",
      title: "Test 11",
      passPoints: 15,
      totalPoints: 25,
      durationMinutes: 45,
      hasPdf: false,
    },
    {
      year: "test12",
      title: "Test 12",
      passPoints: 15,
      totalPoints: 25,
      durationMinutes: 45,
      hasPdf: false,
    },
  ],
};
