import type { Question } from "../../data/types";

export const questions: Question[] = [
  {
    id: "ccse_modelo_q1",
    examId: "modelo-ccse",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question:
      "¿Con qué rey se restaura la democracia en España después del régimen de Franco?",
    options: ["Con Juan Carlos I.", "Con Carlos III.", "Con Alfonso XIII."],
    correctAnswer: "a",
  },
  {
    id: "ccse_modelo_q2",
    examId: "modelo-ccse",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question:
      "Los municipios y provincias forman parte de la Administración...",
    options: ["local.", "autonómica.", "central."],
    correctAnswer: "a",
  },
  {
    id: "ccse_modelo_q3",
    examId: "modelo-ccse",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "Los españoles pueden votar a partir de los...",
    options: ["18 años.", "21 años.", "16 años."],
    correctAnswer: "a",
  },
  {
    id: "ccse_modelo_q4",
    examId: "modelo-ccse",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question:
      "¿Cuál de los siguientes cuerpos forma parte de las Fuerzas Armadas de España?",
    options: [
      "El Ejército del Aire.",
      "La Guardia Civil.",
      "la Policía Foral.",
    ],
    correctAnswer: "a",
  },
  {
    id: "ccse_modelo_q5",
    examId: "modelo-ccse",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "¿Qué título tiene la futura reina, hija del rey?",
    options: [
      "Duquesa de Alba.",
      "Princesa de Aragón.",
      "Princesa de Asturias.",
    ],
    correctAnswer: "c",
  },
  {
    id: "ccse_modelo_q6",
    examId: "modelo-ccse",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question:
      "¿Cómo se llama la organización que defiende los intereses de los trabajadores?",
    options: ["asociación.", "sindicato.", "partido."],
    correctAnswer: "b",
  },
  {
    id: "ccse_modelo_q7",
    examId: "modelo-ccse",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question:
      "¿Qué organismo oficial atiende las quejas de los ciudadanos por el mal funcionamiento de las administraciones?",
    options: [
      "El Defensor del Pueblo.",
      "La Policía Nacional.",
      "La Oficina de Atención al Consumidor.",
    ],
    correctAnswer: "a",
  },
  {
    id: "ccse_modelo_q8",
    examId: "modelo-ccse",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "Las Cortes Generales están compuestas por el Senado y...",
    options: [
      "el Tribunal Supremo.",
      "el Congreso de los Diputados.",
      "el Consejo de Estado.",
    ],
    correctAnswer: "b",
  },
  {
    id: "ccse_modelo_q9",
    examId: "modelo-ccse",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question:
      "¿Quién es el representante del Estado en una comunidad autónoma?",
    options: [
      "El presidente de la comunidad autónoma.",
      "El delegado del Gobierno.",
      "El presidente de la Asamblea autonómica.",
    ],
    correctAnswer: "b",
  },
  {
    id: "ccse_modelo_q10",
    examId: "modelo-ccse",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "El Defensor del Pueblo depende de...",
    options: [
      "el Consejo de ministros.",
      "el Tribunal Cuentas.",
      "las Cortes Generales.",
    ],
    correctAnswer: "c",
  },
  {
    id: "ccse_modelo_q11",
    examId: "modelo-ccse",
    topic: "tarea-2",
    type: "mc",
    points: 1,
    question:
      "Se garantiza el secreto de las comunicaciones de los españoles, salvo resolución judicial.",
    options: ["Verdadero", "Falso"],
    correctAnswer: "a",
  },
  {
    id: "ccse_modelo_q12",
    examId: "modelo-ccse",
    topic: "tarea-2",
    type: "mc",
    points: 1,
    question: "La atención sanitaria es gratuita.",
    options: ["Verdadero", "Falso"],
    correctAnswer: "a",
  },
  {
    id: "ccse_modelo_q13",
    examId: "modelo-ccse",
    topic: "tarea-2",
    type: "mc",
    points: 1,
    question:
      "La Educación Primaria (de 6 a 12 años) es obligatoria y gratuita.",
    options: ["Verdadero", "Falso"],
    correctAnswer: "a",
  },
  {
    id: "ccse_modelo_q14",
    examId: "modelo-ccse",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question: "Canarias tiene un clima...",
    options: ["oceánico.", "mediterráneo.", "subtropical."],
    correctAnswer: "c",
  },
  {
    id: "ccse_modelo_q15",
    examId: "modelo-ccse",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question: "¿Cuál de estos ríos desemboca en el mar Mediterráneo?",
    options: ["El Tajo.", "El Duero.", "El Júcar."],
    correctAnswer: "c",
  },
  {
    id: "ccse_modelo_q16",
    examId: "modelo-ccse",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question: "¿Qué tres culturas convivieron en la España medieval?",
    options: [
      "La cristiana, la judía y la musulmana.",
      "La griega, la cristiana y la judía.",
      "La fenicia, la judía y la musulmana.",
    ],
    correctAnswer: "a",
  },
  {
    id: "ccse_modelo_q17",
    examId: "modelo-ccse",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question:
      "¿Qué escritora española escribe en otra lengua oficial de España?",
    options: ["Ana María Matute.", "Mercè Rodoreda.", "Almudena Grandes."],
    correctAnswer: "b",
  },
  {
    id: "ccse_modelo_q18",
    examId: "modelo-ccse",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question: "¿Quién fue Clara Campoamor?",
    options: [
      "Una defensora de los derechos de la mujer.",
      "Una directora de cine.",
      "Una cantante lírica.",
    ],
    correctAnswer: "a",
  },
  {
    id: "ccse_modelo_q19",
    examId: "modelo-ccse",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "¿Dónde se tramita la tarjeta sanitaria?",
    options: [
      "En el Ministerio de Sanidad.",
      "En la comisaría de policía.",
      "En el centro de salud.",
    ],
    correctAnswer: "c",
  },
  {
    id: "ccse_modelo_q20",
    examId: "modelo-ccse",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "El horario de Canarias, con respecto a la Península, es de...",
    options: ["dos horas menos.", "una hora más.", "una hora menos."],
    correctAnswer: "c",
  },
  {
    id: "ccse_modelo_q21",
    examId: "modelo-ccse",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "El Camino de Santiago es...",
    options: [
      "Patrimonio de la Humanidad.",
      "Una ruta para excursionistas.",
      "Una vía de ferrocarril.",
    ],
    correctAnswer: "a",
  },
  {
    id: "ccse_modelo_q22",
    examId: "modelo-ccse",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "¿A qué hora se cena normalmente en España?",
    options: ["A las 18 h.", "A las 21 o 22 h.", "A las 23 h."],
    correctAnswer: "b",
  },
  {
    id: "ccse_modelo_q23",
    examId: "modelo-ccse",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question:
      "La organización que trabaja para conseguir la integración de las personas con discapacidad visual es...",
    options: ["UNICEF.", "Cáritas.", "la ONCE."],
    correctAnswer: "c",
  },
  {
    id: "ccse_modelo_q24",
    examId: "modelo-ccse",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question:
      "¿Cuándo se puede llamar al número de teléfono para atención a víctimas de violencia de género?",
    options: [
      "De lunes a viernes.",
      "En horario de mañana.",
      "Las 24 horas del día.",
    ],
    correctAnswer: "c",
  },
  {
    id: "ccse_modelo_q25",
    examId: "modelo-ccse",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question:
      "¿Qué título se obtiene tras realizar una tesis doctoral en España?",
    options: ["Máster.", "Graduado.", "Doctor."],
    correctAnswer: "c",
  },
  {
    id: "ccse_test1_q1",
    examId: "test1",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "España es...",
    options: [
      "una monarquía parlamentaria",
      "una república federal",
      "una monarquía federal",
    ],
    correctAnswer: "a",
  },
  {
    id: "ccse_test1_q2",
    examId: "test1",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "La ley fundamental de España se llama...",
    options: ["Constitución", "Ley básica", "Ordenamiento esencial"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test1_q3",
    examId: "test1",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "El Instituto de las Mujeres es…",
    options: ["una institución europea", "un organismo español", "un ONG"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test1_q4",
    examId: "test1",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: '¿Cuándo puedo hacer los trámites en la sede electrónica?"',
    options: [
      "En cualquier horario",
      "únicamente por la mañana",
      "De lunes a viernes",
    ],
    correctAnswer: "a",
  },
  {
    id: "ccse_test1_q5",
    examId: "test1",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question:
      "Los convenios colectivos de una empresa son los que se firman con los representantes de los trabajadores sobre...",
    options: [
      "las condiciones laborales",
      "el futuro de la empresa",
      "la relación con los clientes",
    ],
    correctAnswer: "a",
  },
  {
    id: "ccse_test1_q6",
    examId: "test1",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question: "El castellano o español es lengua oficial...",
    options: [
      "en toda España",
      "solo donde no hay otras lenguas",
      "en toda la Península Ibérica",
    ],
    correctAnswer: "a",
  },
  {
    id: "ccse_test1_q7",
    examId: "test1",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question: "¿Cuál de estas fuerzas de seguridad es de ámbito autonómico?",
    options: ["Policía local", "Guardia Civil", "Policía Foral de Navarra"],
    correctAnswer: "c",
  },
  {
    id: "ccse_test1_q8",
    examId: "test1",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question: "¿Qué fuerza de seguridad está en toda España?",
    options: [
      "La Policía Foral de Navarra.",
      "El Cuerpo Nacional de Policía.",
      "Los Mossos.",
    ],
    correctAnswer: "b",
  },
  {
    id: "ccse_test1_q9",
    examId: "test1",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question:
      "En la Constitución se establece la separación de poderes: el poder ejecutivo, el legislativo y el...",
    options: ["judicial", "informativo", "político"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test1_q10",
    examId: "test1",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "La bandera de España debe utilizarse...",
    options: [
      "solo los días de fiesta local",
      "en todos los edificios públicos",
      "solo en actos del Gobierno español",
    ],
    correctAnswer: "b",
  },
  {
    id: "ccse_test1_q11",
    examId: "test1",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question: "¿Quién fue el primer rey de España?",
    options: ["Fernando VII", "Carlos I", "Juan Carlos I"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test1_q12",
    examId: "test1",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question: "La gestión de la sanidad es competencia de...",
    options: ["el Estado", "las comunidades autónomas", "los ayuntamientos"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test1_q13",
    examId: "test1",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question:
      "¿Quién fue el primer presidente del Gobierno de España en democracia?",
    options: ["Mariano Rajoy", "Adolfo Suárez", "José Luis Rodriguez Zapatero"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test1_q14",
    examId: "test1",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question:
      "¿Cuál de estos organismos se encarga de interpretar la Constitución?",
    options: [
      "EL Poder Constitucional",
      "El Tribunal Constitucional",
      "EL Consejo General del Poder Judicial",
    ],
    correctAnswer: "b",
  },
  {
    id: "ccse_test1_q15",
    examId: "test1",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "¿Quién modera el funcionamiento de las instituciones españolas?",
    options: [
      "el presidente del Gobierno",
      "el rey",
      "El Directo de la Real Academia Española",
    ],
    correctAnswer: "b",
  },
  {
    id: "ccse_test1_q16",
    examId: "test1",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question:
      "¿Cómo se llama la cámara de representación territorial en España?",
    options: ["Senado", "Diputación permanente", "Congreso de los Diputados"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test1_q17",
    examId: "test1",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question:
      "¿Qué se necesita para hacer trámites por internet con la Administración?",
    options: [
      "Un pasaporte válido",
      "Una firma electrónica",
      "Una firma en papel",
    ],
    correctAnswer: "b",
  },
  {
    id: "ccse_test1_q18",
    examId: "test1",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "¿Cómo se aprobó la Constitución?",
    options: ["Por ley", "en referendúm", "lo mandó el rey"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test1_q19",
    examId: "test1",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question:
      "¿Cómo se llama la ley más importante de cada comunidad autónoma?",
    options: [
      "Estatuto de Autonomía",
      "Normativa autonómica",
      "Ley de la Comunidad",
    ],
    correctAnswer: "a",
  },
  {
    id: "ccse_test1_q20",
    examId: "test1",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question:
      "Las instalaciones culturales y deportivas públicas son competencia del...",
    options: [
      "Ayuntamiento",
      "Ministerio de Educación, Formación Profesional y Deportes",
      "Ministerio de Igualdad",
    ],
    correctAnswer: "a",
  },
  {
    id: "ccse_test1_q21",
    examId: "test1",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "¿Quién dirige la administración militar de España?",
    options: ["Los ayuntamiento", "El Gobierno", "Las Cortes Generales"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test1_q22",
    examId: "test1",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question: "¿Qué hay en las islas Baleares, en vez de diputaciones?",
    options: ["Cabildos", "Consejos insulares", "Centros de diputados"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test1_q23",
    examId: "test1",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question: "¿Qué ciudad tiene más habitantes?",
    options: ["Sevilla", "Barcelona", "Zaragoza"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test1_q24",
    examId: "test1",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "Las Cortes Generales representan",
    options: [
      "al pueblo español",
      "a los partidos políticos",
      "a los ministros",
    ],
    correctAnswer: "a",
  },
  {
    id: "ccse_test1_q25",
    examId: "test1",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question:
      "El Congreso de los Diputados y el Senado constituyen el poder...",
    options: ["ejecutivo", "legislativo", "judicial"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test2_q1",
    examId: "test2",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "¿Qué ley dicta el Gobierno en casos de especial urgencia?",
    options: ["El decreto ley", "La ley ordinaria", "la ley orgánica"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test2_q2",
    examId: "test2",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question: "¿Cuántas comunidades autónomas hay en España?",
    options: ["8", "17", "25"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test2_q3",
    examId: "test2",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "Los colores de la bandera española son...",
    options: ["blanco y rojo", "rojo y amarillo", "amarillo y blanco"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test2_q4",
    examId: "test2",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "¿Dónde está la sede del Gobierno?",
    options: ["Madrid", "En Barcelona", "En Sevilla"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test2_q5",
    examId: "test2",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question:
      "La bandera azul con 12 estrellas amarillas en círculo es la bandera de...",
    options: [
      "La Unión Europea",
      "El Parlamento Europeo",
      "la Comisión Europea",
    ],
    correctAnswer: "a",
  },
  {
    id: "ccse_test2_q6",
    examId: "test2",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "En las elecciones municipales se vota a...",
    options: [
      "alcaldes y concejales",
      "ministros y ministras",
      "diputados y senadores",
    ],
    correctAnswer: "a",
  },
  {
    id: "ccse_test2_q7",
    examId: "test2",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question: "¿Qué lengua es oficial en País Vasco?",
    options: ["El bable", "El aragonés", "El euskera"],
    correctAnswer: "c",
  },
  {
    id: "ccse_test2_q8",
    examId: "test2",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "Todos los españoles tienen el deber de conocer la lengua...",
    options: [
      "autonómica del Estado",
      "oficial del Estado",
      "local del Estado",
    ],
    correctAnswer: "b",
  },
  {
    id: "ccse_test2_q9",
    examId: "test2",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question:
      "El aranés es una lengua cooficial que se habla en un pequeño territorio de…",
    options: ["Cataluña", "La Rioja", "Aragón"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test2_q10",
    examId: "test2",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question:
      "Las instituciones de una comunidad autónoma son: la asamblea legislativa, el consejo de gobierno y...",
    options: ["la diputación", "el presidente", "el delegado de gobierno"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test2_q11",
    examId: "test2",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question:
      "¿Cuál de estas opciones es una lengua cooficial en alguna comunidad autónoma?",
    options: ["el gallego", "el aragonés", "el murciano"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test2_q12",
    examId: "test2",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question:
      "¿Qué institución tiene como fin la promoción de la enseñanza de la lengua española y la difusión de la cultura en español?",
    options: [
      "El Instituto Nacional de Administración Pública",
      "EL Istituto Nacional de Estadística",
      "El Instituto Cervantes",
    ],
    correctAnswer: "c",
  },
  {
    id: "ccse_test2_q13",
    examId: "test2",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question:
      "¿Cuál de los siguientes organismos trabaja para conseguir la normalización lingüística?",
    options: [
      "el institut Ramon Llull",
      "el Instituto Cervantes",
      "La Real Academia Española",
    ],
    correctAnswer: "c",
  },
  {
    id: "ccse_test2_q14",
    examId: "test2",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "¿Dónde vive el presidente del Gobierno?",
    options: [
      "En el Palacio Real",
      "En el Palacio de la Zarzuela",
      "En el Palacio d la Moncloa",
    ],
    correctAnswer: "c",
  },
  {
    id: "ccse_test2_q15",
    examId: "test2",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question:
      "¿Cuál de los siguientes cuerpos forma parte de las Fuerzas Armadas de España?",
    options: ["la Policia Foral", "La Guardia Civil", "El Ejército del Aire"],
    correctAnswer: "c",
  },
  {
    id: "ccse_test2_q16",
    examId: "test2",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "¿Quiénes forman parte del Gobierno?",
    options: ["los ministros", "los concejales", "los alcaldes"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test2_q17",
    examId: "test2",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "España es un...",
    options: [
      "estado social y democrático de Derecho",
      "estado libre asociado",
      "estado confederado",
    ],
    correctAnswer: "a",
  },
  {
    id: "ccse_test2_q18",
    examId: "test2",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question:
      "¿Cuál de las siguientes siglas corresponde a un partido político?",
    options: ["PP", "PIB", "UE"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test2_q19",
    examId: "test2",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "¿Qué título tiene la futura reina, hija del rey?",
    options: ["Princesa de Asturias", "Princesa de Aragón", "Duquesa de Alba"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test2_q20",
    examId: "test2",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question:
      "¿Con qué rey se restaura la democracia en España después del régimen de Franco?",
    options: ["Con Carlos III", "Con Alfonso XIII", "Con Juan Carlos I"],
    correctAnswer: "c",
  },
  {
    id: "ccse_test2_q21",
    examId: "test2",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "¿En qué año se aprobó la Constitución española?",
    options: ["en 1957", "en 1978", "en 2011"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test2_q22",
    examId: "test2",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question: "¿Cuántas comunidades autónomas tienen su propia bandera?",
    options: ["ninguna", "todas", "las que tiene una lengua cooficial"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test2_q23",
    examId: "test2",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question:
      "¿Qué organismo oficial atiende las quejas de los ciudadanos por el mal funcionamiento de las administraciones?",
    options: [
      "La Oficina de Atención al Consumidor",
      "La Policía Nacional",
      "El Defensor del Pueblo",
    ],
    correctAnswer: "c",
  },
  {
    id: "ccse_test2_q24",
    examId: "test2",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question:
      "¿Cuántas firmas, como mínimo, deben recoger los ciudadanos para poder presentar una proposición de ley?",
    options: ["250 000", "100 000", "500 000"],
    correctAnswer: "c",
  },
  {
    id: "ccse_test2_q25",
    examId: "test2",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question:
      "¿A cuál de estas organizaciones internacionales pertenece España?",
    options: [
      "Al Mercado Común del Sur (MERCOSUR)",
      "La Organización de las Naciones Unidas (ONU)",
      "A la Unión Económica Euroasiática",
    ],
    correctAnswer: "b",
  },
  {
    id: "ccse_test3_q1",
    examId: "test3",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question:
      "En la organización de la Administración se distinguen tres niveles: central, autonómica y...",
    options: ["estatal", "regional", "local"],
    correctAnswer: "c",
  },
  {
    id: "ccse_test3_q2",
    examId: "test3",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "El poder legislativo corresponde...",
    options: [
      "al presidente y los ministros",
      "a los jueces y magistrados",
      "a los diputados y senadores",
    ],
    correctAnswer: "c",
  },
  {
    id: "ccse_test3_q3",
    examId: "test3",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "¿Dónde vive el rey?",
    options: [
      "en el Palacio de la Moneda",
      "En el Palacio de la Zarzuela",
      "En el Palacio de la Moncloa",
    ],
    correctAnswer: "b",
  },
  {
    id: "ccse_test3_q4",
    examId: "test3",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "El nombre oficial del parlamento español es...",
    options: ["Cortes Generales", "Congreso de los Diputados", "Senado"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test3_q5",
    examId: "test3",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question:
      "El Gobierno está formado por el presidente, uno o más vicepresidentes y los...",
    options: ["concejales", "ministros", "gobernadores"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test3_q6",
    examId: "test3",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "¿Quién puede reinar en España?",
    options: [
      "solo los hombres",
      "solo las mujeres",
      "tanto los hombres como las mujeres",
    ],
    correctAnswer: "c",
  },
  {
    id: "ccse_test3_q7",
    examId: "test3",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "El Tribunal de Cuentas depende de...",
    options: [
      "La Presidencia del Gobierno",
      "las Cortes Generales",
      "el Ministerio de Hacienda",
    ],
    correctAnswer: "b",
  },
  {
    id: "ccse_test3_q8",
    examId: "test3",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question:
      "¿Quién es la tercera autoridad del Estado, después del rey y el presidente del Gobierno?",
    options: [
      "El presidente del Senado",
      "el ministro de Economía",
      "El presidente del Congreso de los Diputados",
    ],
    correctAnswer: "c",
  },
  {
    id: "ccse_test3_q9",
    examId: "test3",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question: "¿Qué lengua cooficial se habla en las islas Baleares?",
    options: ["Gallego", "Catalán", "Euskera"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test3_q10",
    examId: "test3",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question:
      "La Constitución defiende valores tales como la libertad, la igualdad, el pluralismo político",
    options: ["la justicia", "la solidaridad", "la fraternidad"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test3_q11",
    examId: "test3",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question: "¿Cuántos kilómetros cuadrados tiene España, más o menos?",
    options: ["100 000", "500 000", "1 000 000"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test3_q12",
    examId: "test3",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question: "¿Cuántos habitantes tiene España?",
    options: ["95 millones", "49 millones", "67 millones"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test3_q13",
    examId: "test3",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "¿Cuál de estos es un órgano consultivo del Gobierno de España?",
    options: [
      "El Parlamento Europeo",
      "El Consejo de Estado",
      "El Tribunal Constitucional",
    ],
    correctAnswer: "b",
  },
  {
    id: "ccse_test3_q14",
    examId: "test3",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "¿Quién dirige la política interior y exterior de España?",
    options: ["El rey", "El Gobierno", "EL Congreso de los Diputados"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test3_q15",
    examId: "test3",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "El Defensor del Pueblo depende de...",
    options: [
      "el Consejo de Ministros",
      "el Tribunal de Cuentas",
      "las Cortes Generales",
    ],
    correctAnswer: "c",
  },
  {
    id: "ccse_test3_q16",
    examId: "test3",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question: "El Instituto Etxepare tiene como misión la difusión del...",
    options: [
      "euskera y la cultura vasca",
      "balbe y la cultura cántabra",
      "gallego y la cultura galaica",
    ],
    correctAnswer: "a",
  },
  {
    id: "ccse_test3_q17",
    examId: "test3",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question: "La Comunidad Iberoamericana de Naciones está formada por...",
    options: [
      "22 países de América y Europa",
      "América del Sur y España",
      "todos los países donde se habla español",
    ],
    correctAnswer: "a",
  },
  {
    id: "ccse_test3_q18",
    examId: "test3",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question:
      "La Secretaría Xeral de Política Lingüística difunde y promociona la lengua y la cultura…",
    options: ["catalanas", "gallegas", "vascas"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test3_q19",
    examId: "test3",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "¿Cómo se llama el rey de España?",
    options: ["Juan Carlos I", "Felipe VI", "Afonso XIII"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test3_q20",
    examId: "test3",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question:
      "¿Cómo se llama el órgano de gobierno de los jueces y magistrados?",
    options: [
      "Tribunal Supremo",
      "Consejo General del Poder Judicial",
      "Consejo de Estado",
    ],
    correctAnswer: "b",
  },
  {
    id: "ccse_test3_q21",
    examId: "test3",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "¿Quién aprueba los presupuestos generales del Estado?",
    options: ["Las Cortes Generales", "La Junta Electoral Central", "El rey"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test3_q22",
    examId: "test3",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "La Constitución española es...",
    options: ["la ley fundamental", "parte de otra ley", "una ley secundaria"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test3_q23",
    examId: "test3",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "Las Cortes Generales están compuestas por el Senado y...",
    options: [
      "el Congreso de los Diputados",
      "el Tribunal Supremo",
      "El Consejo de Estado",
    ],
    correctAnswer: "a",
  },
  {
    id: "ccse_test3_q24",
    examId: "test3",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "¿Quién elabora las leyes?",
    options: [
      "el poder ejecutivo",
      "el poder legislativo",
      "el poder judicial",
    ],
    correctAnswer: "b",
  },
  {
    id: "ccse_test3_q25",
    examId: "test3",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question:
      "La defensa de la integridad territorial de España corresponde a...",
    options: [
      "la Policía Nacional y la Guardia Civil",
      "las Fuerzas Armadas",
      "la Policía Nacional y las policías autonómicas",
    ],
    correctAnswer: "b",
  },
  {
    id: "ccse_test4_q1",
    examId: "test4",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question:
      "El Ejército español participa desde 1989 en misiones de paz de la...",
    options: [
      "Organización de Estado Iberoamericanos (OEI)",
      "Unión Europea Occidental (UEO)",
      "Organización de Naciones Unidas (ONU)",
    ],
    correctAnswer: "c",
  },
  {
    id: "ccse_test4_q2",
    examId: "test4",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "¿Quién vigila puertos y aeropuertos, fronteras y costas?",
    options: ["la Guardia Civil", "La Policía Local", "la Policía Nacional"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test4_q3",
    examId: "test4",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question:
      "¿Quién hace el control de pasaportes en las fronteras de España?",
    options: ["la Guardia Civil", "La Policía Local", "la Policía Nacional"],
    correctAnswer: "c",
  },
  {
    id: "ccse_test4_q4",
    examId: "test4",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "¿Quién controla la circulación de coches en las ciudades?",
    options: ["la Guardia Civil", "La Policía Local", "La Policía Nacional"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test4_q5",
    examId: "test4",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "¿Cómo se llama la policía autonómica de Cataluña?",
    options: ["Guardia Civil", "Ertzaintza", "Mossos d´Equadra"],
    correctAnswer: "c",
  },
  {
    id: "ccse_test4_q6",
    examId: "test4",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "¿Cómo se llama la policía autonómica del País Vasco?",
    options: ["Ertzaintza", "Guardia Civil", "Mosso d`Esquadra"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test4_q7",
    examId: "test4",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "¿Desde qué año es rey Felipe VI?",
    options: ["Desde 1975", "Desde 2014", "Desde 2020"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test4_q8",
    examId: "test4",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "¿Quién regula el tráfico en los pueblos y ciudades?",
    options: ["La Guardia Civil", "Protección Civil", "La Policía Local"],
    correctAnswer: "c",
  },
  {
    id: "ccse_test4_q9",
    examId: "test4",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "¿Quién puede presentar una queja al Defensor del Pueblo?",
    options: [
      "Solo los ciudadanos legalmente residentes",
      "solo los españoles mayores de 18 años",
      "todos los ciudadanos españoles o extranjeros",
    ],
    correctAnswer: "c",
  },
  {
    id: "ccse_test4_q10",
    examId: "test4",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "En España el voto en las elecciones es...",
    options: ["un derecho", "un deber", "una obligación"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test4_q11",
    examId: "test4",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "¿Quién vigila el tráfico en las carreteras?",
    options: [
      "La Guardia Civil",
      "La Policía Nacional",
      "El Ejército de Tierra",
    ],
    correctAnswer: "a",
  },
  {
    id: "ccse_test4_q12",
    examId: "test4",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "¿Qué organismo se encarga de recaudar los impuestos?",
    options: [
      "El Tribunal de Cuentas",
      "la Agencia Tributaria",
      "El Consejo Económico y Social",
    ],
    correctAnswer: "b",
  },
  {
    id: "ccse_test4_q13",
    examId: "test4",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "¿Dónde se publican las leyes nacionales?",
    options: [
      "En el Boletin del Instittuo Nacional de Estadística (INE)",
      "En el Portal de la Administración Electrónica (PAe)",
      "En el Boletin Oficial del Estado (BOE)",
    ],
    correctAnswer: "c",
  },
  {
    id: "ccse_test4_q14",
    examId: "test4",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question:
      "¿Cómo se llaman los órganos de gobierno que solo existen en Canarias?",
    options: ["Cabildos", "Consejos Insulares", "Diputaciones"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test4_q15",
    examId: "test4",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question:
      "¿Dónde ofrece el Gobierno toda la información sobre novedades e iniciativas de la Administración electrónica?",
    options: [
      "En el INE (Instituto Nacional de Estadística)",
      "En el BOE (Boletín Oficial del Estado)",
      "En el PAe (Portal de Administración Electrónica)",
    ],
    correctAnswer: "c",
  },
  {
    id: "ccse_test4_q16",
    examId: "test4",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question:
      "¿Cuál es el número de teléfono de información de la Administración General del Estado?",
    options: ["010", "060", "091"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test4_q17",
    examId: "test4",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question: "España está organizada en...",
    options: ["cantones", "comunidades autónomas", "estados federales"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test4_q18",
    examId: "test4",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "¿Cuántos partidos políticos hay en España?",
    options: ["ninguno", "uno", "muchos"],
    correctAnswer: "c",
  },
  {
    id: "ccse_test4_q19",
    examId: "test4",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "¿Dónde tiene lugar la investidura del presidente del Gobierno?",
    options: [
      "En el Palacio de la Moncloa",
      "En el Congreso de los Diputados",
      "En el Senado",
    ],
    correctAnswer: "b",
  },
  {
    id: "ccse_test4_q20",
    examId: "test4",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "¿Quién tiene el mando supremo de las Fuerzas Armadas?",
    options: ["El rey", "El presidente del Gobierno", "El ministro de Defensa"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test4_q21",
    examId: "test4",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question:
      "¿Quién es el representante del Estado en una Comunidad Autónoma?",
    options: [
      "El presidente de la Comundiad Autónoma",
      "El delegado del Gobierno",
      "el Presidente de la Asamblea autonómica",
    ],
    correctAnswer: "b",
  },
  {
    id: "ccse_test4_q22",
    examId: "test4",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question: "¿Cuántas provincias hay en España?",
    options: ["45", "50", "55"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test4_q23",
    examId: "test4",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question: "La enseñanza de las lenguas cooficiales es competencia...",
    options: ["del Estado", "de la comunidad autónoma", "de la provincia"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test4_q24",
    examId: "test4",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "El poder ejecutivo corresponde...",
    options: [
      "el Gobierno del Estado",
      "al Congreso y al Senado",
      "a los jueces y magistrados",
    ],
    correctAnswer: "a",
  },
  {
    id: "ccse_test4_q25",
    examId: "test4",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "¿Cuántas cámaras hay en el Parlamento español?",
    options: ["una", "dos", "tres"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test5_q1",
    examId: "test5",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question:
      "El suministro de agua y el alumbrado de las ciudades es competencia de …",
    options: [
      "el ayuntamiento",
      "El Gobierno autonómico",
      "el Ministerio de Obras Públicas y Urbanismo",
    ],
    correctAnswer: "a",
  },
  {
    id: "ccse_test5_q2",
    examId: "test5",
    topic: "tarea-2",
    type: "mc",
    points: 1,
    question:
      "En materias como nacionalidad, inmigración, emigración o extranjería solo tiene competencia...",
    options: ["El Estado", "Las comunidades Autónomas", "Los ayuntamientos"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test5_q3",
    examId: "test5",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question: "¿Cuántas mujeres han sido presidentas de Gobierno en España?",
    options: ["Ninguna", "Una", "Dos"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test5_q4",
    examId: "test5",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "Las relaciones internacionales son competencia de...",
    options: ["El Estado", "Las comunidades autónomas", "Los ayuntamientos"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test5_q5",
    examId: "test5",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question: "El ayuntamiento está formado por el alcalde y...",
    options: ["Los concejales", "Los diputados", "Los senadores"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test5_q6",
    examId: "test5",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question: "¿Quiénes forman el gobierno de las comunidades autónomas?",
    options: [
      "El presidente y los ministros",
      "El alcalde y los concejales",
      "El presidente y los consejeros",
    ],
    correctAnswer: "c",
  },
  {
    id: "ccse_test5_q7",
    examId: "test5",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question: "¿Cuál es el órgano de gobierno en los municipios?",
    options: ["El ayuntamiento", "La diputación", "El cabildo"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test5_q8",
    examId: "test5",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question:
      "¿Cómo se llaman los órganos de gobierno de las provincias españolas?",
    options: ["Cabildos", "Consejos Insulares", "Diputaciones"],
    correctAnswer: "c",
  },
  {
    id: "ccse_test5_q9",
    examId: "test5",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "¿Cuál es el órgano superior del poder ejecutvio?",
    options: ["EL Gobierno", "Las Fuerzas Armadas", "Las Cortes Generales"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test5_q10",
    examId: "test5",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question: "El idioma español también se llama…",
    options: ["aragonés", "castellano", "leonés"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test5_q11",
    examId: "test5",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "¿A quiénes se elige en las elecciones al Parlamento Europeo?",
    options: [
      "A los ministros europeos",
      "A los consejeros delegados",
      "A los eurodiputados",
    ],
    correctAnswer: "c",
  },
  {
    id: "ccse_test5_q12",
    examId: "test5",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "Los españoles pueden votar a partir de los…",
    options: ["16 años", "18 años", "21 años"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test5_q13",
    examId: "test5",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "Algunos ciudadanos extranjeros pueden votar en las elecciones…",
    options: ["municipales", "autonómicas", "generales"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test5_q14",
    examId: "test5",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "¿Quién controla la gestión financiera del Estado?",
    options: [
      "El Banco de España",
      "La Agencia Tributaria",
      "El Tribunal de Cuentas",
    ],
    correctAnswer: "c",
  },
  {
    id: "ccse_test5_q15",
    examId: "test5",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "¿A quiénes se elige en las elecciones generales?",
    options: [
      "A los senadores y diputados",
      "A los eurodiputados",
      "A los concejales",
    ],
    correctAnswer: "a",
  },
  {
    id: "ccse_test5_q16",
    examId: "test5",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "¿Cuántos miembros tiene el Congreso de los Diputados?",
    options: ["300", "350", "400"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test5_q17",
    examId: "test5",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question: "Los municipios y provincias forman parte de la Administración…",
    options: ["autonómica", "local", "central"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test5_q18",
    examId: "test5",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question: "La comunidad autónoma más poblada de España es…",
    options: ["Andalucía", "Cataluña", "Castilla y León"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test5_q19",
    examId: "test5",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question:
      "¿Cómo se llama la organización que defiende los intereses de los trabajadores?",
    options: ["Asociación", "Partido", "Sindicato"],
    correctAnswer: "c",
  },
  {
    id: "ccse_test5_q20",
    examId: "test5",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question:
      "¿Cuál de las siguientes personalidades ha sido presidente del Gobierno de España?",
    options: ["José María Aznar", "Manuel Fraga", "Dolores Ibárruri"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test5_q21",
    examId: "test5",
    topic: "tarea-2",
    type: "mc",
    points: 1,
    question:
      "En España, la Constitución obliga a todos los ciudadanos a practicar una religión",
    options: ["Verdadero", "Falso"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test5_q22",
    examId: "test5",
    topic: "tarea-2",
    type: "mc",
    points: 1,
    question:
      "Los españoles que obtienen la nacionalidad por residencia deben esperar tres años para poder votar en las elecciones.",
    options: ["Verdadero", "Falso"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test5_q23",
    examId: "test5",
    topic: "tarea-2",
    type: "mc",
    points: 1,
    question:
      "En España, la Constitución prohíbe la tortura y la pena de muerte.",
    options: ["Verdadero", "Falso"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test5_q24",
    examId: "test5",
    topic: "tarea-2",
    type: "mc",
    points: 1,
    question:
      "El funcionamiento de los partidos políticos tiene que ser democrático",
    options: ["Verdadero", "Falso"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test5_q25",
    examId: "test5",
    topic: "tarea-2",
    type: "mc",
    points: 1,
    question:
      "Se puede obligar a alguien a decir cuáles son sus ideas políticas o religiosas",
    options: ["Verdadero", "Falso"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test6_q1",
    examId: "test6",
    topic: "tarea-2",
    type: "mc",
    points: 1,
    question:
      "Se puede limitar a una persona el derecho a entrar y salir libremente de España por motivos ideológicos.",
    options: ["Verdadero", "Falso"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test6_q2",
    examId: "test6",
    topic: "tarea-2",
    type: "mc",
    points: 1,
    question:
      "La Educación Primaria (de 6 a 12 años) es gratuita y obligatoria.",
    options: ["Verdadero", "Falso"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test6_q3",
    examId: "test6",
    topic: "tarea-2",
    type: "mc",
    points: 1,
    question:
      "La Constitución garantiza el derecho de los españoles a una vivienda digna.",
    options: ["Verdadero", "Falso"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test6_q4",
    examId: "test6",
    topic: "tarea-2",
    type: "mc",
    points: 1,
    question:
      "En España la policía puede entrar en cualquier casa sin resolución judicial en cualquier momento.",
    options: ["Verdadero", "Falso"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test6_q5",
    examId: "test6",
    topic: "tarea-2",
    type: "mc",
    points: 1,
    question:
      "Se garantiza el secreto de las comunicaciones de los españoles, salvo resolución judicial.",
    options: ["Verdadero", "Falso"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test6_q6",
    examId: "test6",
    topic: "tarea-2",
    type: "mc",
    points: 1,
    question:
      "Todos los españoles, ya sean mayores o menores de edad, tiene derecho a votar en las elecciones.",
    options: ["Verdadero", "Falso"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test6_q7",
    examId: "test6",
    topic: "tarea-2",
    type: "mc",
    points: 1,
    question:
      "Los profesores pueden enseñar con libertad, dentro de los límites de la Constitución.",
    options: ["Verdadero", "Falso"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test6_q8",
    examId: "test6",
    topic: "tarea-2",
    type: "mc",
    points: 1,
    question:
      "La Constitución reconoce únicamente los derechos fundamentales de los españoles.",
    options: ["Verdadero", "Falso"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test6_q9",
    examId: "test6",
    topic: "tarea-2",
    type: "mc",
    points: 1,
    question: "En España existe la pena de muerte",
    options: ["Verdadero", "Falso"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test6_q10",
    examId: "test6",
    topic: "tarea-2",
    type: "mc",
    points: 1,
    question:
      "La Ley limita el acceso de terceras personas a datos de carácter personal.",
    options: ["Verdadero", "Falso"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test6_q11",
    examId: "test6",
    topic: "tarea-2",
    type: "mc",
    points: 1,
    question:
      "La libertad de prensa está limitada por el respeto al honor de las personas.",
    options: ["Verdadero", "Falso"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test6_q12",
    examId: "test6",
    topic: "tarea-2",
    type: "mc",
    points: 1,
    question:
      "Es España las causas de separación y divorcio están reguladas por ley.",
    options: ["Verdadero", "Falso"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test6_q13",
    examId: "test6",
    topic: "tarea-2",
    type: "mc",
    points: 1,
    question: "Todos los españoles pagan la misma cantidad de impuestos.",
    options: ["Vedadero", "Falso"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test6_q14",
    examId: "test6",
    topic: "tarea-2",
    type: "mc",
    points: 1,
    question: "En España los hombres y las mujeres tienen los mismos derechos.",
    options: ["Verdadero", "Falso"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test6_q15",
    examId: "test6",
    topic: "tarea-2",
    type: "mc",
    points: 1,
    question:
      "La enseñanza obligatoria consta de dos etapas: Educación Primaria y Educación Secundaria Obligatoria.",
    options: ["Verdadero", "Falso"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test6_q16",
    examId: "test6",
    topic: "tarea-2",
    type: "mc",
    points: 1,
    question: "En España hay una religión oficial.",
    options: ["Verdadero", "Falso"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test6_q17",
    examId: "test6",
    topic: "tarea-2",
    type: "mc",
    points: 1,
    question: "La atención sanitaria pública es gratuita",
    options: ["Verdadero", "Falso"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test6_q18",
    examId: "test6",
    topic: "tarea-2",
    type: "mc",
    points: 1,
    question:
      "Los poderes públicos deben promover la educación física y el deporte.",
    options: ["Verdadero", "Falso"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test6_q19",
    examId: "test6",
    topic: "tarea-2",
    type: "mc",
    points: 1,
    question: "En España está reconocido el derecho de asociación.",
    options: ["Verdadero", "Falso"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test6_q20",
    examId: "test6",
    topic: "tarea-2",
    type: "mc",
    points: 1,
    question:
      "En caso de huelga, es obligatorio por ley mantener unos servicios mínimos.",
    options: ["Verdadero", "Falso"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test6_q21",
    examId: "test6",
    topic: "tarea-2",
    type: "mc",
    points: 1,
    question: "Los trabajadores tienen derecho a huelga.",
    options: ["Verdadero", "Falso"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test6_q22",
    examId: "test6",
    topic: "tarea-2",
    type: "mc",
    points: 1,
    question:
      "La libertad ideológica está garantizada solo en parte del territorio nacional.",
    options: ["Verdadero", "Falso"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test6_q23",
    examId: "test6",
    topic: "tarea-2",
    type: "mc",
    points: 1,
    question:
      "Todos los ciudadanos tienen acceso al sistema de Seguridad Social público, excepto si están desempleados.",
    options: ["Verdadero", "Falso"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test6_q24",
    examId: "test6",
    topic: "tarea-2",
    type: "mc",
    points: 1,
    question:
      "Todos tienen derecho a disfrutar de un medio ambiente adecuado para el desarrollo de la persona, así como el deber de conservarlo.",
    options: ["Verdadero", "Falso"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test6_q25",
    examId: "test6",
    topic: "tarea-2",
    type: "mc",
    points: 1,
    question: "Todo el mundo tiene derecho a expresar su opinión.",
    options: ["Verdadero", "Falso"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test7_q1",
    examId: "test7",
    topic: "tarea-2",
    type: "mc",
    points: 1,
    question: "La edad mínima para casarse en España es de 12 años.",
    options: ["Verdadero", "Falso"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test7_q2",
    examId: "test7",
    topic: "tarea-2",
    type: "mc",
    points: 1,
    question:
      "La Ley prohíbe la discriminación por cualquier circunstancia personal o social.",
    options: ["Verdadero", "Falso"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test7_q3",
    examId: "test7",
    topic: "tarea-2",
    type: "mc",
    points: 1,
    question: "Los poderes públicos garantizan la defensa de los consumidores.",
    options: ["Verdadero", "Falso"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test7_q4",
    examId: "test7",
    topic: "tarea-2",
    type: "mc",
    points: 1,
    question:
      "Según la Constitución, la administración de Justicia corresponde exclusivamente al Estado español.",
    options: ["Verdadero", "Falso"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test7_q5",
    examId: "test7",
    topic: "tarea-2",
    type: "mc",
    points: 1,
    question:
      "Los españoles deben ayudar en los casos de catástrofe o calamidad pública.",
    options: ["Verdadero", "Falso"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test7_q6",
    examId: "test7",
    topic: "tarea-2",
    type: "mc",
    points: 1,
    question:
      "En España los ciudadanos pueden elegir en qué ciudad quieren vivir.",
    options: ["Verdadero", "Falso"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test7_q7",
    examId: "test7",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question: "¿Dónde están Cáceres y Badajoz?",
    options: ["En el Principado de Asturias", "En Andalucía", "En Extremadura"],
    correctAnswer: "c",
  },
  {
    id: "ccse_test7_q8",
    examId: "test7",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question: "¿Cuál es la capital de la Comunidad Valenciana",
    options: ["Alicante", "Castellon", "Valencia"],
    correctAnswer: "c",
  },
  {
    id: "ccse_test7_q9",
    examId: "test7",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question: "¿Dónde están las islas Baleares?",
    options: [
      "En el mar Cantábrico",
      "En el mar Mediterráneo",
      "En el océano Atlántico",
    ],
    correctAnswer: "b",
  },
  {
    id: "ccse_test7_q10",
    examId: "test7",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question:
      "¿Cómo se llama la extensa llanura situada en el centro de la península ibérica?",
    options: ["Marisma", "Cordillera", "Meseta"],
    correctAnswer: "c",
  },
  {
    id: "ccse_test7_q11",
    examId: "test7",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question: "El parque nacional de Ordesa está en...",
    options: ["Aragón", "Navarra", "Castilla La Mancha"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test7_q12",
    examId: "test7",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question: "¿En qué comunidad autónoma están Guadalajara y Cuenca?",
    options: ["En Castilla y León", "En Castilla-La Mancha", "En Cantabria"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test7_q13",
    examId: "test7",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question: "¿De qué comunidad autónoma es capital Mérida?",
    options: ["De Valencia", "De Cataluña", "De Extremadura"],
    correctAnswer: "c",
  },
  {
    id: "ccse_test7_q14",
    examId: "test7",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question: "¿Dónde está Almería?",
    options: ["En Andalucía", "En Canarias", "En Aragón"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test7_q15",
    examId: "test7",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question: "La capital de la Comunidad Autónoma de Galicia es…",
    options: ["A Coruña", "Vigo", "Santiago de Compostela"],
    correctAnswer: "c",
  },
  {
    id: "ccse_test7_q16",
    examId: "test7",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question: "¿Cuál de estos climas es propio de España?",
    options: ["Polar", "Mediterráneo", "Tropical"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test7_q17",
    examId: "test7",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question: "¿Dónde está el monte Aneto?",
    options: ["En los Pirineos", "En el Sistema Central", "En Sierra Nevada"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test7_q18",
    examId: "test7",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question: "La ciudad de Vitoria es la sede administrativa de...",
    options: ["Navarra", "País Vasco", "La Rioja"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test7_q19",
    examId: "test7",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question: "España se divide en…",
    options: [
      "departamentos y regiones.",
      "comunidades y ciudades autónomas.",
      "regiones autónomas y distritos.",
    ],
    correctAnswer: "b",
  },
  {
    id: "ccse_test7_q20",
    examId: "test7",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question: "¿Cuál de estas comunidades autónomas tiene solo una provincia?",
    options: ["La Rioja", "Aragón", "Galicia"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test7_q21",
    examId: "test7",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question: "En el norte de África están Ceuta y…",
    options: ["Almería", "Melilla", "Cádiz"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test7_q22",
    examId: "test7",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question:
      "¿Cuál de estas comunidades autónomas tiene más de una provincia?",
    options: ["Asturias", "Madrid", "Castilla-La Mancha"],
    correctAnswer: "c",
  },
  {
    id: "ccse_test7_q23",
    examId: "test7",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question: "¿Cuál de estos ríos desemboca en el océano Atlántico?",
    options: ["El Guadalquivir", "El Manzanares", "El Júcar"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test7_q24",
    examId: "test7",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question:
      "¿Cuál de estas provincias forma parte de la Comunidad de Castilla-León?",
    options: ["Burgos", "Huesca", "Guadalajara"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test7_q25",
    examId: "test7",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question:
      "Las temperaturas suaves con abundantes lluvias son propias del clima…",
    options: ["continental.", "oceánico.", "subtropical."],
    correctAnswer: "b",
  },
  {
    id: "ccse_test8_q1",
    examId: "test8",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question: "Canarias tiene un clima...",
    options: ["mediterráneo", "eceánico", "subtropical"],
    correctAnswer: "c",
  },
  {
    id: "ccse_test8_q2",
    examId: "test8",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question: "El principal río que desemboca en el mar Mediterráneo es el...",
    options: ["Ebro", "Duero", "Tajo"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test8_q3",
    examId: "test8",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question: "España está entre los países de Europa más...",
    options: ["lluviosos", "montañosos", "fríos"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test8_q4",
    examId: "test8",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question: "¿En qué provincia está el parque nacional de Monfragüe?",
    options: ["En Cáceres", "En Murcia", "En Ciudad Real"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test8_q5",
    examId: "test8",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question: "Los Picos de Europa están en...",
    options: ["Andalucía", "Cataluña", "Asturias"],
    correctAnswer: "c",
  },
  {
    id: "ccse_test8_q6",
    examId: "test8",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question:
      "Los personajes principales de la novela el Quijote son don Quijote y...",
    options: ["Don Juan", "Sancho Panza", "Doña Inés"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test8_q7",
    examId: "test8",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question:
      "¿Cuál de las siguientes mujeres es una científica española reconocida mundialmente?",
    options: ["Montserrat Caballé", "Ana María Matute", "Margarita Salas"],
    correctAnswer: "c",
  },
  {
    id: "ccse_test8_q8",
    examId: "test8",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question: "¿Qué instrumento musical es típico del folclore español?",
    options: ["EL piano", "EL Violín", "La Guitarra"],
    correctAnswer: "c",
  },
  {
    id: "ccse_test8_q9",
    examId: "test8",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question: "¿Cómo se llama, en literatura, a los siglos XVI y XVII?",
    options: ["siglos de oro", "siglos de plata", "siglos de platino"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test8_q10",
    examId: "test8",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question: "María Zambrano, María Teresa León y Rosa Chacel son...",
    options: ["pintoras", "escritoras", "deportistas"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test8_q11",
    examId: "test8",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question: "¿Qué músico compuso El amor brujo?",
    options: ["Manuel Falla", "Isaac Albeniz", "Joaquín Rodrigo"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test8_q12",
    examId: "test8",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question: "¿Qué dulce es típico de las navidades?",
    options: ["el flan", "el turrón", "la coca"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test8_q13",
    examId: "test8",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question: "Isabel Coixet es una...",
    options: ["cantante pop", "bailarina clásica", "directora de cine"],
    correctAnswer: "c",
  },
  {
    id: "ccse_test8_q14",
    examId: "test8",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question: "Una de las cantantes españolas más famosas actualmente es...",
    options: ["Rosalía", "Marisol", "Lola Flores"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test8_q15",
    examId: "test8",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question:
      "¿En qué ciudad de España hay una mezquita que es Patrimonio de la Humanidad?",
    options: ["Santiago de Compostela", "Madrid", "Córdoba"],
    correctAnswer: "c",
  },
  {
    id: "ccse_test8_q16",
    examId: "test8",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question:
      "¿En qué ciudad de España se encuentra La Alhambra, que es Patrimonio de la Humanidad?",
    options: ["En Sevilla", "En Córdoba", "En Granada"],
    correctAnswer: "c",
  },
  {
    id: "ccse_test8_q17",
    examId: "test8",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question:
      "¿Cuál es el nombre de la directora española que ha destacado por su mirada crítica y por modernizar el cine nacional?",
    options: ["Pilar Miró", "Sara Baras", "Penélope Cruz"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test8_q18",
    examId: "test8",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question: "Pablo Picasso fue un famoso...",
    options: ["pintor", "músico", "escritor"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test8_q19",
    examId: "test8",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question:
      "¿Cómo se llama la mayor institución pública dedicada a la investigación en España?",
    options: [
      "Real Academia Española (RAE)",
      "Consejo Superior de investigaciones Científicas (CSIC)",
      "La Sociedad General de Autores (SGAE)",
    ],
    correctAnswer: "b",
  },
  {
    id: "ccse_test8_q20",
    examId: "test8",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question: "Paco de Lucía fue un famoso....",
    options: ["científico", "guitarrista", "pintos"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test8_q21",
    examId: "test8",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question:
      "¿Cuál de estas manifestaciones folclóricas es patrimonio cultural inmaterial de la humanidad?",
    options: ["el flamenco", "la jota", "la sardana"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test8_q22",
    examId: "test8",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "¿Cuál es la moneda común en muchos países de la Unión Europea?",
    options: ["el dólar", "el peso", "el euro"],
    correctAnswer: "c",
  },
  {
    id: "ccse_test8_q23",
    examId: "test8",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question: "La fiesta de la Tomatina se celebra en...",
    options: ["Mérida", "Buñol", "Santiago de Compostela"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test8_q24",
    examId: "test8",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question:
      "La Feria del Libro se celebra en toda España, normalmente, en...",
    options: ["invierno", "primavera", "verano"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test8_q25",
    examId: "test8",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "La Liga y la Copa del Rey son competiciones de...",
    options: ["natación", "atletismo", "fútbol"],
    correctAnswer: "c",
  },
  {
    id: "ccse_test9_q1",
    examId: "test9",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question: "¿Quién ha recibido el premio Nobel de Literatura?",
    options: ["María Zambrano", "Pablo Picasso", "Vicente Aleixandre"],
    correctAnswer: "c",
  },
  {
    id: "ccse_test9_q2",
    examId: "test9",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question: "Las chirigotas de Cádiz son típicas de…",
    options: ["la Semana Santa", "los carnavales", "las verbenas de verano"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test9_q3",
    examId: "test9",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question: "Teresa Perales y Daniel Molina son...",
    options: ["Campeones paralímpicos", "músicos famosos", "artistas de cine"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test9_q4",
    examId: "test9",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question:
      "¿Qué toman los españoles la noche del 31 de diciembre para celebrar el cambio de año?",
    options: ["lentejas", "uvas", "aceitunas"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test9_q5",
    examId: "test9",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question: "¿Qué científica española es reconocida por sus investigaciones?",
    options: ["Almudena Grandes", "Montserrat Caballé", "Margarita Salas"],
    correctAnswer: "c",
  },
  {
    id: "ccse_test9_q6",
    examId: "test9",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question: "¿Dónde se celebra un famoso festival de cine?",
    options: ["En San Sebastián", "En Cuenca", "En Vigo"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test9_q7",
    examId: "test9",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question:
      "¿Qué escritora española escribe en otra lengua oficial de España?",
    options: ["Mercè Rodoreda", "Almudena Grandes", "Ana María Matute"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test9_q8",
    examId: "test9",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question: "¿Qué tres culturas convivieron en la España medieval?",
    options: [
      "la cristiana, la judía y la musulmana",
      "la fenicia, la judía y la musulana",
      "la griega, la cristiana y la judía",
    ],
    correctAnswer: "a",
  },
  {
    id: "ccse_test9_q9",
    examId: "test9",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "El 6 de diciembre se celebra en España...",
    options: [
      "el Día de la Constitución",
      "la llegada de Colón a América",
      "el Día del Libro",
    ],
    correctAnswer: "a",
  },
  {
    id: "ccse_test9_q10",
    examId: "test9",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question:
      "¿Dónde se encuentran las Cuevas de Altamira que son Patrimonio de la Humanidad?",
    options: ["En Cataluña", "En Aragón", "En Cantabria"],
    correctAnswer: "c",
  },
  {
    id: "ccse_test9_q11",
    examId: "test9",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question: "La Transición española a la democracia comienza en...",
    options: ["1936", "1975", "1982"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test9_q12",
    examId: "test9",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question: "El Premio Cervantes se da a...",
    options: ["actores", "escritores", "pintores"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test9_q13",
    examId: "test9",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question: "Los Premios Goya están relacionados con...",
    options: ["el cine", "la literatura", "la pintura"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test9_q14",
    examId: "test9",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question:
      "¿Qué premios promueven en España valores científicos, culturales y humanísticos?",
    options: [
      "Los Premios Cervantes",
      "Los Premios Princesa de Asturias",
      "Los Premios Goya",
    ],
    correctAnswer: "b",
  },
  {
    id: "ccse_test9_q15",
    examId: "test9",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question: "¿Cuándo fueron los Juegos Olímpicos de Barcelona?",
    options: ["En 1992", "En 1996", "En 2004"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test9_q16",
    examId: "test9",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question: "¿Cuál de estos deportistas juega al tenis?",
    options: ["Pau Gasol", "Carlos Sainz", "Carlos Alcaraz"],
    correctAnswer: "c",
  },
  {
    id: "ccse_test9_q17",
    examId: "test9",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "¿Quién hace el DNI?",
    options: ["la Policía Nacional", "La Guardia Civil", "La Policía Local"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test9_q18",
    examId: "test9",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question:
      "¿Cuál es el documento que certifica el lugar de residencia del titular?",
    options: [
      "EL certificado de empadronamiento",
      "la partida de nacimiento",
      "el carné de conducir",
    ],
    correctAnswer: "a",
  },
  {
    id: "ccse_test9_q19",
    examId: "test9",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "¿A qué sustituye el registro electrónico individual?",
    options: ["AL DNI", "Al permiso de conducir", "Al libro de familia"],
    correctAnswer: "c",
  },
  {
    id: "ccse_test9_q20",
    examId: "test9",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "¿Cuál es la edad mínima para conducir en España?",
    options: ["16 años", "18 años", "20 años"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test9_q21",
    examId: "test9",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "El carné de conducir se hace en...",
    options: [
      "la Dirección General de Tráfico (DGT)",
      "la Policía Nacional",
      "el Registro Civil",
    ],
    correctAnswer: "a",
  },
  {
    id: "ccse_test9_q22",
    examId: "test9",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "Para sacar el carné de conducir hay que aprobar...",
    options: [
      "un examen teórico",
      "un examen práctico",
      "un examen teórico y otro práctico",
    ],
    correctAnswer: "c",
  },
  {
    id: "ccse_test9_q23",
    examId: "test9",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "¿Dónde se tramita el libro de familia?",
    options: [
      "En el Registro Civil",
      "En la Seguridad Social",
      "En las comisarias de policía",
    ],
    correctAnswer: "a",
  },
  {
    id: "ccse_test9_q24",
    examId: "test9",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question: "¿Cuál de estos canales de televisión es autonómico?",
    options: ["Telecinco", "Nova", "El canal Sur"],
    correctAnswer: "c",
  },
  {
    id: "ccse_test9_q25",
    examId: "test9",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "¿Cuánto dura el permiso de maternidad o paternidad?",
    options: ["12 semanas", "16 semanas", "22 semanas"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test10_q1",
    examId: "test10",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question:
      "¿Cuál es la tasa máxima de alcohol en sangre permitida a los conductores, en gramos por litro (g/l)?",
    options: ["0,5", "0,7", "0,9"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test10_q2",
    examId: "test10",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "Las viviendas de protección oficial…",
    options: [
      "tienen un precio limitado.",
      "son para los funcionarios.",
      "tienen sistema de vigilancia.",
    ],
    correctAnswer: "a",
  },
  {
    id: "ccse_test10_q3",
    examId: "test10",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question:
      "¿Qué comunidad autónoma es conocida por la calidad de su aceite de oliva?",
    options: ["Cantabria", "Andalucía", "La Rioja"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test10_q4",
    examId: "test10",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question:
      "¿Cómo se llama la revisión que deben pasar obligatoriamente los coches?",
    options: [
      "IBI (Impuesto sobre Bienes Inmuebles)",
      "ITV (Inspección Técnica de Vehículos)",
      "ITE (Inspección Técnica de Edificios)",
    ],
    correctAnswer: "b",
  },
  {
    id: "ccse_test10_q5",
    examId: "test10",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question:
      "El aperitivo que acompaña a la bebida en bares y restaurantes se llama...",
    options: ["bocadillo.", "tapa.", "primer plato."],
    correctAnswer: "b",
  },
  {
    id: "ccse_test10_q6",
    examId: "test10",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "¿Dónde se tramita la tarjeta sanitaria?",
    options: [
      "En la comisaría de policía",
      "En el centro de salud",
      "En el Ministerio de Sanidad",
    ],
    correctAnswer: "b",
  },
  {
    id: "ccse_test10_q7",
    examId: "test10",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "¿Con cuántos hijos una familia es numerosa?",
    options: ["Con 1 hijo", "Con 2 hijos", "Con 3 hijos"],
    correctAnswer: "c",
  },
  {
    id: "ccse_test10_q8",
    examId: "test10",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "En España está permitido el matrimonio…",
    options: [
      "solo entre personas del mismo sexo.",
      "entre personas del mismo y diferente sexo.",
      "solo entre personas de diferente sexo.",
    ],
    correctAnswer: "b",
  },
  {
    id: "ccse_test10_q9",
    examId: "test10",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "Los propietarios de perros deben registrarlos en…",
    options: [
      "el Ministerio de Justicia.",
      "la comisaría de policía.",
      "el Ayuntamiento.",
    ],
    correctAnswer: "c",
  },
  {
    id: "ccse_test10_q10",
    examId: "test10",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question:
      "Los principales ingredientes de la tortilla española son huevos y…",
    options: ["pimientos.", "patatas.", "tomates."],
    correctAnswer: "b",
  },
  {
    id: "ccse_test10_q11",
    examId: "test10",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question: "¿Quién es un cocinero famoso dentro y fuera de España?",
    options: ["José Andrés", "Rafael Nadal", "Josep Carreras"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test10_q12",
    examId: "test10",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "¿Cuál de estos canales de televisión es público?",
    options: ["Tele5", "La 1", "Antena 3."],
    correctAnswer: "b",
  },
  {
    id: "ccse_test10_q13",
    examId: "test10",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "En una comunidad de vecinos, una de las normas es…",
    options: [
      "abrir la puerta al cartero.",
      "no molestar con ruido.",
      "limpiar los espacios comunes.",
    ],
    correctAnswer: "b",
  },
  {
    id: "ccse_test10_q14",
    examId: "test10",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question: "La sangría es una bebida compuesta por refrescos, vino y…",
    options: ["fruta.", "té.", "agua."],
    correctAnswer: "a",
  },
  {
    id: "ccse_test10_q15",
    examId: "test10",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question: "La sidra es una bebida típica de…",
    options: ["Asturias.", "Valencia.", "Canarias."],
    correctAnswer: "a",
  },
  {
    id: "ccse_test10_q16",
    examId: "test10",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "Los españoles tienen dos apellidos, el primero es…",
    options: [
      "obligatoriamente el de la madre.",
      "obligatoriamente el del padre.",
      "puede ser el de la madre o el del padre.",
    ],
    correctAnswer: "c",
  },
  {
    id: "ccse_test10_q17",
    examId: "test10",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question: "La Fiesta Nacional de España es el…",
    options: ["6 de diciembre.", "15 de agosto.", "12 de octubre."],
    correctAnswer: "c",
  },
  {
    id: "ccse_test10_q18",
    examId: "test10",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question:
      "¿Cuál es el horario habitual de los hipermercados y centros comerciales?",
    options: ["De 9:00 a 17:00 h", "De 10:00 a 22:00 h", "De 8:00 a 23:00 h"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test10_q19",
    examId: "test10",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "¿Dónde se hace el pasaporte?",
    options: [
      "En el registro civil",
      "En una comisaría de policía",
      "En el Ayuntamiento",
    ],
    correctAnswer: "b",
  },
  {
    id: "ccse_test10_q20",
    examId: "test10",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question:
      "El Ministerio de Igualdad es el encargado de luchar contra la violencia de género y la…",
    options: ["separación.", "discriminación.", "solidaridad."],
    correctAnswer: "b",
  },
  {
    id: "ccse_test10_q21",
    examId: "test10",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question:
      "¿Cuál de estas regiones es conocida por sus vinos con denominación de origen?",
    options: ["Ribera de Duero", "Pirineos", "La Vera"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test10_q22",
    examId: "test10",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "El DNI se hace…",
    options: ["por internet.", "en persona.", "por teléfono."],
    correctAnswer: "b",
  },
  {
    id: "ccse_test10_q23",
    examId: "test10",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question: "El horario de Canarias, con respecto a la Península, es de…",
    options: ["dos horas menos.", "una hora menos.", "una hora más."],
    correctAnswer: "b",
  },
  {
    id: "ccse_test10_q24",
    examId: "test10",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question:
      "Para acceder a la Universidad se debe superar una prueba de evaluación llamada…",
    options: [
      "Selectividad",
      "Examen preuniversitario.",
      "Prueba de Acceso a la Universidad",
    ],
    correctAnswer: "c",
  },
  {
    id: "ccse_test10_q25",
    examId: "test10",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question:
      "¿Cuál de estos productos necesita importar España de otros países?",
    options: ["Petróleo", "Aceite de oliva", "Medicamentos"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test11_q1",
    examId: "test11",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question:
      "¿Qué tipo de impuestos tienen que pagar los ciudadanos en España?",
    options: [
      "impuestos directos como el IRPF",
      "impuestos indirectos como el IVA",
      "impuestos directos e indirectos",
    ],
    correctAnswer: "c",
  },
  {
    id: "ccse_test11_q2",
    examId: "test11",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question:
      "Los adultos sin Bachillerato pueden estudiar en la Universidad haciendo una prueba especial a partir de los…",
    options: ["18 años.", "23 años.", "25 años."],
    correctAnswer: "c",
  },
  {
    id: "ccse_test11_q3",
    examId: "test11",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question:
      "¿Dónde puede encontrarse la siguiente norma «Dejar salir antes de entrar»?",
    options: [
      "En el transporte público",
      "En parques y jardines",
      "En instalaciones deportivas",
    ],
    correctAnswer: "a",
  },
  {
    id: "ccse_test11_q4",
    examId: "test11",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "El Bachillerato en España…",
    options: [
      "es obligatorio.",
      "se compone de dos cursos académicos.",
      "es la enseñanza a alumnos de 14 a 16 años.",
    ],
    correctAnswer: "b",
  },
  {
    id: "ccse_test11_q5",
    examId: "test11",
    topic: "tarea-1",
    type: "mc",
    points: 1,
    question: "El Impuesto sobre el Valor Añadido (IVA) forma parte de los…",
    options: [
      "impuestos indirectos.",
      "impuestos sobre la renta.",
      "impuestos sobre sociedades.",
    ],
    correctAnswer: "a",
  },
  {
    id: "ccse_test11_q6",
    examId: "test11",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question:
      "¿Qué número reciben los trabajadores al comenzar su primer empleo?",
    options: [
      "El de la Seguridad Social",
      "El del pasaporte",
      "El número de servicio",
    ],
    correctAnswer: "a",
  },
  {
    id: "ccse_test11_q7",
    examId: "test11",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "Los colegios públicos…",
    options: [
      "pueden decidir su número de plazas.",
      "pueden contratar los profesores que quieran.",
      "son gratuitos.",
    ],
    correctAnswer: "c",
  },
  {
    id: "ccse_test11_q8",
    examId: "test11",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question: "¿Cuál de estos puertos es uno de los principales de España?",
    options: ["Tenerife", "Alicante", "Algeciras"],
    correctAnswer: "c",
  },
  {
    id: "ccse_test11_q9",
    examId: "test11",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "Un colegio concertado es un colegio privado que…",
    options: [
      "recibe dinero de la Administración.",
      "financian los padres de los alumnos.",
      "recibe dinero de los bancos.",
    ],
    correctAnswer: "a",
  },
  {
    id: "ccse_test11_q10",
    examId: "test11",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "España exporta productos principalmente a países…",
    options: [
      "de Hispanoamérica.",
      "de la Unión Europea.",
      "del Norte de África.",
    ],
    correctAnswer: "b",
  },
  {
    id: "ccse_test11_q11",
    examId: "test11",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "Las bibliotecas públicas son gratuitas para…",
    options: ["todos.", "los parados.", "los niños."],
    correctAnswer: "a",
  },
  {
    id: "ccse_test11_q12",
    examId: "test11",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "¿Cuál de estos productos exporta España más que importa?",
    options: ["Gas", "Ropa", "Calzado"],
    correctAnswer: "c",
  },
  {
    id: "ccse_test11_q13",
    examId: "test11",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question:
      "Una persona mayor de 18 años puede obtener el título de Graduado en Educación Secundaria Obligatoria en…",
    options: [
      "un Centro de Educación de Personas Adultas.",
      "un centro de enseñanza Primaria.",
      "una universidad.",
    ],
    correctAnswer: "a",
  },
  {
    id: "ccse_test11_q14",
    examId: "test11",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "La formación profesional…",
    options: [
      "es para mayores de 25 años.",
      "puede ser de grado medio o superior.",
      "es obligatoria.",
    ],
    correctAnswer: "b",
  },
  {
    id: "ccse_test11_q15",
    examId: "test11",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "¿Adónde vamos para ver al médico de familia o al pediatra?",
    options: ["Al hospital", "Al centro de salud", "A la farmacia"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test11_q16",
    examId: "test11",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "¿Para cuántos años vale la tarjeta sanitaria europea?",
    options: ["Para un año", "Para dos años", "Para 10 años"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test11_q17",
    examId: "test11",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "¿A qué hora se cena normalmente en España?",
    options: ["A las 18 h", "A las 20 h", "A las 21 o 22 h"],
    correctAnswer: "c",
  },
  {
    id: "ccse_test11_q18",
    examId: "test11",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "¿Cuál es el número de teléfono único para cualquier emergencia?",
    options: ["060", "112", "911"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test11_q19",
    examId: "test11",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "¿Cuál es un periódico deportivo?",
    options: ["ABC", "As", "Cinco días"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test11_q20",
    examId: "test11",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "¿Dónde se venden sellos y tabaco?",
    options: ["En el quiosco", "En la farmacia", "En el estanco"],
    correctAnswer: "c",
  },
  {
    id: "ccse_test11_q21",
    examId: "test11",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "¿Cómo se llama el tren español de alta velocidad?",
    options: ["AVE", "TGV", "Eurostar"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test11_q22",
    examId: "test11",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question:
      "La organización que trabaja para conseguir la integración de las personas con discapacidad visual es…",
    options: ["la ONCE", "Unicef", "Cáritas"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test11_q23",
    examId: "test11",
    topic: "tarea-4",
    type: "mc",
    points: 1,
    question: "El Camino de Santiago es…",
    options: [
      "Patrimonio de la Humanidad.",
      "una vía de ferrocarril.",
      "una ruta para excursionistas.",
    ],
    correctAnswer: "a",
  },
  {
    id: "ccse_test11_q24",
    examId: "test11",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question:
      "¿Cuál es el canal de televisión estatal que transmite noticias de actualidad nacional e internacional continuamente?",
    options: ["Teledeporte", "La 1", "Canal 24 horas"],
    correctAnswer: "c",
  },
  {
    id: "ccse_test11_q25",
    examId: "test11",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question:
      "El teléfono gratuito para las víctimas de violencia de género es el…",
    options: ["091", "112", "016"],
    correctAnswer: "c",
  },
  {
    id: "ccse_test12_q1",
    examId: "test12",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question:
      "En España, la red de trenes puede ser de larga distancia, de media distancia y…",
    options: ["de cercanías.", "rural.", "transnacional."],
    correctAnswer: "a",
  },
  {
    id: "ccse_test12_q2",
    examId: "test12",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question:
      "¿Qué está prohibido hacer en la puerta de un hospital o colegio?",
    options: ["Fumar", "Comer", "Beber"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test12_q3",
    examId: "test12",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "Cuando compramos 250 gramos de un alimento estamos comprando…",
    options: ["medio kilo.", "un cuarto de kilo.", "un tercio de kilo."],
    correctAnswer: "b",
  },
  {
    id: "ccse_test12_q4",
    examId: "test12",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question:
      "Si compramos una botella de agua de 750 ml, compramos una botella de…",
    options: ["tres cuartos de litro.", "medio litro.", "un litro."],
    correctAnswer: "a",
  },
  {
    id: "ccse_test12_q5",
    examId: "test12",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "¿Dónde se compran las medicinas con receta?",
    options: ["En el hospital", "En el centro de salud", "En la farmacia"],
    correctAnswer: "c",
  },
  {
    id: "ccse_test12_q6",
    examId: "test12",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question:
      "¿Cuál de estas tres recomendaciones podemos encontrar en un parque?",
    options: [
      "No pisar el césped",
      "Se recomienda pagar el billete con el dinero justo",
      "Respetar las normas sobre equipaje",
    ],
    correctAnswer: "a",
  },
  {
    id: "ccse_test12_q7",
    examId: "test12",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question:
      "¿Cuál de las siguientes cosas es obligatoria para el propietario de un coche en España?",
    options: ["El garaje", "El seguro", "La alarma"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test12_q8",
    examId: "test12",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question: "El aeropuerto Adolfo Suárez está en…",
    options: ["Barcelona.", "Madrid.", "Bilbao."],
    correctAnswer: "b",
  },
  {
    id: "ccse_test12_q9",
    examId: "test12",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "En un coche es obligatorio el uso del cinturón de seguridad...",
    options: [
      "solo en el asiento del conductor.",
      "en los asientos delanteros.",
      "en todos los asientos.",
    ],
    correctAnswer: "c",
  },
  {
    id: "ccse_test12_q10",
    examId: "test12",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "¿Cuál es el límite de velocidad en autopista?",
    options: ["90 km/h", "120 km/h", "150 km/h"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test12_q11",
    examId: "test12",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question:
      "Ceder el asiento a las personas con movilidad reducida es una norma que encontramos indicada en…",
    options: ["el transporte público.", "las bibliotecas.", "los museos."],
    correctAnswer: "a",
  },
  {
    id: "ccse_test12_q12",
    examId: "test12",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "¿En qué caso se retira el permiso de conducir?",
    options: [
      "Por accidente grave",
      "Por la pérdida de los puntos",
      "Por exceso de velocidad",
    ],
    correctAnswer: "b",
  },
  {
    id: "ccse_test12_q13",
    examId: "test12",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "¿Qué significa Renfe?",
    options: [
      "Red Nacional de Fondos Europeos",
      "Red Nacional de los Ferrocarriles Españoles",
      "Red Nacional de Fundaciones Estatales",
    ],
    correctAnswer: "b",
  },
  {
    id: "ccse_test12_q14",
    examId: "test12",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "Los españoles necesitan el pasaporte para viajar a…",
    options: ["Italia.", "China.", "Alemania."],
    correctAnswer: "b",
  },
  {
    id: "ccse_test12_q15",
    examId: "test12",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "¿Cuál es la edad mínima para trabajar en España?",
    options: ["16 años", "18 años", "21 años"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test12_q16",
    examId: "test12",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "¿Cuál es el sector de mayor peso en la economía española?",
    options: ["Agricultura", "Servicios", "Construcción"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test12_q17",
    examId: "test12",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "España es innovadora en el sector de…",
    options: [
      "la ingeniería aeroespacial.",
      "las energías renovables.",
      "la energía nuclear.",
    ],
    correctAnswer: "b",
  },
  {
    id: "ccse_test12_q18",
    examId: "test12",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "¿Cómo se llama la ley laboral más importante de España?",
    options: [
      "La Constitución",
      "El Estatuto de los Trabajadores",
      "El Servicio Público de Empleo Estatal",
    ],
    correctAnswer: "b",
  },
  {
    id: "ccse_test12_q19",
    examId: "test12",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question:
      "¿Cuáles de estos establecimientos está abierto 24 horas si es necesario?",
    options: ["Farmacia", "Pescadería", "Librería"],
    correctAnswer: "a",
  },
  {
    id: "ccse_test12_q20",
    examId: "test12",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "La educación infantil en España…",
    options: ["es obligatoria.", "tiene dos ciclos.", "empieza a los 4 años."],
    correctAnswer: "b",
  },
  {
    id: "ccse_test12_q21",
    examId: "test12",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "¿Cuándo empieza el calendario escolar?",
    options: ["En agosto", "En septiembre", "En octubre"],
    correctAnswer: "b",
  },
  {
    id: "ccse_test12_q22",
    examId: "test12",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question: "Las Escuelas Oficiales de Idiomas…",
    options: [
      "son centros de enseñanza privada.",
      "son para mayores de 16 años.",
      "dependen del Instituto Cervantes.",
    ],
    correctAnswer: "b",
  },
  {
    id: "ccse_test12_q23",
    examId: "test12",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question:
      "¿Cómo se llama el documento oficial que recoge las fechas de todos los contratos de trabajo de una persona?",
    options: [
      "Informe de vida laboral",
      "Recibo de finiquito",
      "Certificado de profesionalidad",
    ],
    correctAnswer: "a",
  },
  {
    id: "ccse_test12_q24",
    examId: "test12",
    topic: "tarea-5",
    type: "mc",
    points: 1,
    question:
      "Los convenios colectivos de una empresa son los que se firman con los representantes de los trabajadores sobre...",
    options: [
      "las condiciones laborales",
      "el futuro de la empresa",
      "la relación con los clientes",
    ],
    correctAnswer: "a",
  },
  {
    id: "ccse_test12_q25",
    examId: "test12",
    topic: "tarea-3",
    type: "mc",
    points: 1,
    question:
      "¿Cuál de estas comunidades autónomas tiene el PIB por habitante más alto?",
    options: ["Navarra", "Galicia", "Andalucía"],
    correctAnswer: "a",
  },
];
