import type { SubjectMeta } from "../../data/types";

export const meta: SubjectMeta = {
  id: "esei",
  name: "Sistemas Intelixentes",
  university: "Universidade da Coruña",
  courseCode: "202322",
  icon: "🧠",
  acknowledgments: "Preguntas recopiladas de exámenes oficiales.",
  topics: [
    {
      key: "busqueda",
      label: "Búsqueda y Heurísticas",
      icon: "🔍",
      color: "blue",
    },
    {
      key: "representacion",
      label: "Representación del Conocimiento",
      icon: "🧩",
      color: "indigo",
    },
    {
      key: "logica",
      label: "Lógica Categórica y Bayesiana",
      icon: "📐",
      color: "purple",
    },
    {
      key: "rna",
      label: "Redes Neuronales Artificiales",
      icon: "🧬",
      color: "green",
    },
    {
      key: "som",
      label: "Mapas Autoorganizativos",
      icon: "🗺️",
      color: "amber",
    },
    {
      key: "evolutiva",
      label: "Computación Evolutiva",
      icon: "🧬",
      color: "red",
    },
  ],
  exams: [
    {
      year: "2023",
      title: "2023",
      date: "2023",
      description: "45 preguntas",
      passPoints: 22,
      totalPoints: 45,
      durationMinutes: 120,
      hasPdf: false,
    },
    {
      year: "2024",
      title: "2024",
      date: "2024",
      description: "44 preguntas",
      passPoints: 22,
      totalPoints: 44,
      durationMinutes: 120,
      hasPdf: false,
    },
    {
      year: "2025-05",
      title: "Mayo 2025",
      date: "Mayo 2025",
      description: "42 preguntas",
      passPoints: 21,
      totalPoints: 42,
      durationMinutes: 120,
      hasPdf: false,
    },
    {
      year: "2025-07",
      title: "Julio 2025",
      date: "Julio 2025",
      description: "47 preguntas",
      passPoints: 23,
      totalPoints: 47,
      durationMinutes: 120,
      hasPdf: false,
    },
    {
      year: "2026-06",
      title: "Junio 2026",
      date: "Junio 2026",
      description: "56 preguntas",
      passPoints: 28,
      totalPoints: 56,
      durationMinutes: 120,
      hasPdf: false,
    },
  ],
};
