import type { SubjectMeta } from "../../data/types";

export const meta: SubjectMeta = {
  id: "esei",
  name: "Sistemas Intelixentes",
  university: "Universidade da Coruña",
  courseCode: "202322",
  icon: "🧠",
  contentPolicy: "community-practice",
  acknowledgments:
    "Las preguntas y respuestas incluidas en esta plataforma son ejercicios originales creados por estudiantes anónimos a partir del temario oficial. No se reproducen exámenes oficiales, enunciados originales ni materiales docentes protegidos del profesorado o de la universidad. Si se detecta alguna coincidencia sustancial no autorizada, puede notificarse para su revisión y retirada.",
  topics: [
    {
      key: "t1",
      label: "Tema 1: Introducción",
      icon: "👋",
      color: "blue",
    },
    {
      key: "t2",
      label: "Tema 2: Búsqueda",
      icon: "🔍",
      color: "indigo",
    },
    {
      key: "t3",
      label: "Tema 3: Representación",
      icon: "🧩",
      color: "purple",
    },
    {
      key: "t4",
      label: "Tema 4: Razonamiento",
      icon: "⚖️",
      color: "amber",
    },
    {
      key: "t5",
      label: "Tema 5: Planificación",
      icon: "📅",
      color: "orange",
    },
    {
      key: "t6",
      label: "Tema 6: Introducción a los sistemas subsimbólicos",
      icon: "🧠",
      color: "green",
    },
    {
      key: "t7",
      label: "Tema 7: Redes Neuronales Artificiales: modelos y características",
      icon: "🔬",
      color: "cyan",
    },
    {
      key: "t8",
      label: "Tema 8: Entrenamiento de Redes Neuronales Artificiales",
      icon: "🚀",
      color: "red",
    },
    {
      key: "t9",
      label: "Tema 9: Sistemas autoorganizativos",
      icon: "🗺️",
      color: "pink",
    },
    {
      key: "t10",
      label: "Tema 10: Computación Evolutiva",
      icon: "🧬",
      color: "purple",
    },
  ],
  megatopics: [
    {
      key: "simbolica",
      label: "Simbólica",
      topics: ["t1", "t2", "t3", "t4", "t5"],
    },
    {
      key: "subsimbolica",
      label: "Subsimbólica",
      topics: ["t6", "t7", "t8", "t9", "t10"],
    },
  ],
  exams: [
    {
      year: "2023",
      title: "Posibles preguntas 2023",
      date: "2023",
      description: "45 preguntas",
      passPoints: 22,
      totalPoints: 45,
      durationMinutes: 120,
      hasPdf: false,
    },
    {
      year: "2024",
      title: "Posibles preguntas 2024",
      date: "2024",
      description: "44 preguntas",
      passPoints: 22,
      totalPoints: 44,
      durationMinutes: 120,
      hasPdf: false,
    },
    {
      year: "2025-05",
      title: "Posibles preguntas Mayo 2025",
      date: "Mayo 2025",
      description: "42 preguntas",
      passPoints: 21,
      totalPoints: 42,
      durationMinutes: 120,
      hasPdf: false,
    },
    {
      year: "2025-07",
      title: "Posibles preguntas Julio 2025",
      date: "Julio 2025",
      description: "47 preguntas",
      passPoints: 23,
      totalPoints: 47,
      durationMinutes: 120,
      hasPdf: false,
    },
    {
      year: "2026-06",
      title: "Posibles preguntas Junio 2026",
      date: "Junio 2026",
      description: "56 preguntas",
      passPoints: 28,
      totalPoints: 56,
      durationMinutes: 120,
      hasPdf: false,
    },
  ],
};
