blank_issues_enabled: false
contact_links:
  - name: General Discussion
    url: https://github.com/TeenBiscuits/Pasame-Examenes/discussions
    about: For questions, ideas, and general discussion about the platform.
