import type { SubjectMeta } from "../../data/types";

export const meta: SubjectMeta = {
  id: "cepe",
  name: "Concurrencia e Paralelismo",
  university: "Universidade da Coruña",
  courseCode: "202320",
  icon: "⚡️",
  acknowledgments:
    "Exámenes y soluciones originales proporcionadas por el profesorado de la asignatura.",
  topics: [
    {
      key: "mutex-y-condiciones",
      label: "Mutex y Condiciones",
      icon: "🔒",
      color: "blue",
    },
    {
      key: "erlang",
      label: "Erlang",
      icon: "🧵",
      color: "purple",
    },
    {
      key: "preguntas-teoricas",
      label: "Preguntas Teóricas",
      icon: "📝",
      color: "amber",
    },
    {
      key: "ejercicios-mpi",
      label: "Ejercicios MPI",
      icon: "⚙️",
      color: "green",
    },
  ],
  megatopics: [
    {
      key: "concurrencia",
      label: "Concurrencia",
      topics: ["mutex-y-condiciones", "erlang"],
    },
    {
      key: "paralelismo",
      label: "Paralelismo",
      topics: ["preguntas-teoricas", "ejercicios-mpi"],
    },
  ],
  exams: [
    {
      year: "2018-06",
      title: "Junio 2018",
      date: "Mayo 2018",
      passPoints: 5,
      totalPoints: 10,
      durationMinutes: 180,
      description: "10 points · 5 questions",
      hasPdf: true,
    },
    {
      year: "2018-07",
      title: "Julio 2018",
      date: "Julio 2018",
      passPoints: 5,
      totalPoints: 10,
      durationMinutes: 180,
      description: "10 points · 5 questions",
      hasPdf: true,
    },
    {
      year: "2019-06",
      title: "Junio 2019",
      date: "Mayo 2019",
      passPoints: 5,
      totalPoints: 10,
      durationMinutes: 180,
      description: "10 points · 5 questions",
      hasPdf: true,
    },
    {
      year: "2019-07",
      title: "Julio 2019",
      date: "Julio 2019",
      passPoints: 5,
      totalPoints: 10,
      durationMinutes: 180,
      description: "10 points · 5 questions",
      hasPdf: true,
    },
    {
      year: "2020-06",
      title: "Junio 2020",
      date: "Junio 2020",
      passPoints: 2,
      totalPoints: 4,
      durationMinutes: 180,
      description: "4 points · 5 questions",
      hasPdf: true,
    },
    {
      year: "2020-07",
      title: "Julio 2020",
      date: "Julio 2020",
      passPoints: 2,
      totalPoints: 4,
      durationMinutes: 180,
      description: "4 points · 5 questions",
      hasPdf: true,
    },
    {
      year: "2021-06",
      title: "Junio 2021",
      date: "Junio 2021",
      passPoints: 5,
      totalPoints: 10,
      durationMinutes: 180,
      description: "10 points · 4 questions",
      hasPdf: true,
    },
    {
      year: "2021-07",
      title: "Julio 2021",
      date: "Julio 2021",
      passPoints: 5,
      totalPoints: 10,
      durationMinutes: 180,
      description: "10 points · 4 questions",
      hasPdf: true,
    },
    {
      year: "2022-06",
      title: "Junio 2022",
      date: "Junio 2022",
      passPoints: 5,
      totalPoints: 10,
      durationMinutes: 180,
      description: "10 points · 5 questions",
      hasPdf: true,
    },
    {
      year: "2022-07",
      title: "Julio 2022",
      date: "Julio 2022",
      passPoints: 5,
      totalPoints: 10,
      durationMinutes: 180,
      description: "10 points · 5 questions",
      hasPdf: true,
    },
    {
      year: "2023-06",
      title: "Junio 2023",
      date: "Mayo 2023",
      passPoints: 5,
      totalPoints: 10,
      durationMinutes: 180,
      description: "10 points · 4 questions",
      hasPdf: true,
    },
    {
      year: "2023-07",
      title: "Julio 2023",
      date: "Julio 2023",
      passPoints: 5,
      totalPoints: 10,
      durationMinutes: 180,
      description: "10 points · 4 questions",
      hasPdf: true,
    },
    {
      year: "2024-06",
      title: "Junio 2024",
      date: "Mayo 2024",
      passPoints: 5,
      totalPoints: 10,
      durationMinutes: 180,
      description: "10 points · 5 questions",
      hasPdf: true,
    },
    {
      year: "2024-07",
      title: "Julio 2024",
      date: "Julio 2024",
      passPoints: 5,
      totalPoints: 10,
      durationMinutes: 180,
      description: "10 points · 5 questions",
      hasPdf: true,
    },
    {
      year: "2025-06",
      title: "Junio 2025",
      date: "Mayo 2025",
      passPoints: 5,
      totalPoints: 10,
      durationMinutes: 180,
      description: "10 points · 5 questions",
      hasPdf: true,
    },
    {
      year: "2025-07",
      title: "Julio 2025",
      date: "Julio 2025",
      passPoints: 5,
      totalPoints: 10,
      durationMinutes: 180,
      description: "10 points · 5 questions",
      hasPdf: true,
    },
  ],
};
