import type { SubjectMeta } from "../../data/types";

export const meta: SubjectMeta = {
  id: "cepe",
  name: "Concorrencia e Paralelismo",
  university: "Universidade da Coruña",
  courseCode: "202320",
  icon: "⚡",
  contentPolicy: "authorized-exams",
  acknowledgments:
    "Exámenes y soluciones originales proporcionadas por el profesorado de la asignatura.",
  topics: [
    {
      key: "concurrencia-mutex",
      label: "Mutex y Condiciones",
      icon: "🔒",
      color: "blue",
    },
    {
      key: "concurrencia-erlang",
      label: "Erlang",
      icon: "🧵",
      color: "purple",
    },
    {
      key: "paralelismo-teoria",
      label: "Preguntas Teóricas",
      icon: "📖",
      color: "green",
    },
    {
      key: "paralelismo-mpi",
      label: "Ejercicios de MPI",
      icon: "🔄",
      color: "amber",
    },
  ],
  megatopics: [
    {
      key: "concurrencia",
      label: "Concurrencia",
      topics: ["concurrencia-mutex", "concurrencia-erlang"],
    },
    {
      key: "paralelismo",
      label: "Paralelismo",
      topics: ["paralelismo-teoria", "paralelismo-mpi"],
    },
  ],
  exams: [
    {
      year: "2018-06",
      title: "Mayo 2018",
      date: "Mayo 2018",
      description: "10 puntos · 5 preguntas",
      passPoints: 5,
      totalPoints: 10,
      durationMinutes: 180,
    },
    {
      year: "2018-07",
      title: "Julio 2018",
      date: "Julio 2018",
      description: "10 puntos · 5 preguntas",
      passPoints: 5,
      totalPoints: 10,
      durationMinutes: 180,
    },
    {
      year: "2019-06",
      title: "Mayo 2019",
      date: "Mayo 2019",
      description: "10 puntos · 5 preguntas",
      passPoints: 5,
      totalPoints: 10,
      durationMinutes: 180,
    },
    {
      year: "2019-07",
      title: "Julio 2019",
      date: "Julio 2019",
      description: "10 puntos · 5 preguntas",
      passPoints: 5,
      totalPoints: 10,
      durationMinutes: 180,
    },
    {
      year: "2020-06",
      title: "Junio 2020",
      date: "Junio 2020",
      description: "10 puntos · 5 preguntas",
      passPoints: 5,
      totalPoints: 10,
      durationMinutes: 180,
    },
    {
      year: "2020-07",
      title: "Julio 2020",
      date: "Julio 2020",
      description: "10 puntos · 5 preguntas",
      passPoints: 5,
      totalPoints: 10,
      durationMinutes: 180,
    },
    {
      year: "2021-06",
      title: "Junio 2021",
      date: "Junio 2021",
      description: "10 puntos · 4 preguntas",
      passPoints: 5,
      totalPoints: 10,
      durationMinutes: 180,
    },
    {
      year: "2021-07",
      title: "Julio 2021",
      date: "Julio 2021",
      description: "10 puntos · 4 preguntas",
      passPoints: 5,
      totalPoints: 10,
      durationMinutes: 180,
    },
    {
      year: "2022-06",
      title: "Junio 2022",
      date: "Junio 2022",
      description: "10 puntos · 5 preguntas",
      passPoints: 5,
      totalPoints: 10,
      durationMinutes: 180,
    },
    {
      year: "2022-07",
      title: "Julio 2022",
      date: "Julio 2022",
      description: "10 puntos · 5 preguntas",
      passPoints: 5,
      totalPoints: 10,
      durationMinutes: 180,
    },
    {
      year: "2023-06",
      title: "Mayo 2023",
      date: "Mayo 2023",
      description: "10 puntos · 4 preguntas",
      passPoints: 5,
      totalPoints: 10,
      durationMinutes: 180,
    },
    {
      year: "2023-07",
      title: "Julio 2023",
      date: "Julio 2023",
      description: "10 puntos · 4 preguntas",
      passPoints: 5,
      totalPoints: 10,
      durationMinutes: 180,
    },
    {
      year: "2024-06",
      title: "Junio 2024",
      date: "Junio 2024",
      description: "10 puntos · 5 preguntas",
      passPoints: 5,
      totalPoints: 10,
      durationMinutes: 180,
    },
    {
      year: "2024-07",
      title: "Julio 2024",
      date: "Julio 2024",
      description: "10 puntos · 5 preguntas",
      passPoints: 5,
      totalPoints: 10,
      durationMinutes: 180,
    },
    {
      year: "2025-06",
      title: "Mayo 2025",
      date: "Mayo 2025",
      description: "10 puntos · 5 preguntas",
      passPoints: 5,
      totalPoints: 10,
      durationMinutes: 180,
    },
    {
      year: "2025-07",
      title: "Julio 2025",
      date: "Julio 2025",
      description: "10 puntos · 5 preguntas",
      passPoints: 5,
      totalPoints: 10,
      durationMinutes: 180,
    },
  ],
};
