import type { SubjectMeta } from "../../data/types";

export const meta: SubjectMeta = {
  id: "ece",
  name: "Estrutura de Computadores",
  university: "Universidade da Coruña",
  courseCode: "202314",
  icon: "💻",
  acknowledgments:
    "Exámenes y soluciones originales proporcionadas por el profesorado de la asignatura.",
  topics: [
    { key: "rendimiento", label: "Rendimiento", icon: "⚡", color: "blue" },
    { key: "segmentacion", label: "Segmentación", icon: "🔄", color: "green" },
    { key: "cache", label: "Memoria caché", icon: "💾", color: "purple" },
    {
      key: "memoria-virtual",
      label: "Memoria virtual",
      icon: "📄",
      color: "amber",
    },
    { key: "buses", label: "Buses y E/S", icon: "🔌", color: "red" },
    { key: "raid", label: "RAID y almacenamiento", icon: "🗄️", color: "cyan" },
  ],
  exams: [
    {
      year: "2021-01",
      title: "Enero 2021",
      date: "Enero 2021",
      description: "4 puntos · 4 preguntas",
      passPoints: 2,
      totalPoints: 4,
      durationMinutes: 120,
    },
    {
      year: "2021-07",
      title: "Julio 2021",
      date: "Julio 2021",
      description: "4 puntos · 4 preguntas",
      passPoints: 2,
      totalPoints: 4,
      durationMinutes: 120,
    },
    {
      year: "2022-01",
      title: "Enero 2022",
      date: "Enero 2022",
      description: "4 puntos · 4 preguntas",
      passPoints: 2,
      totalPoints: 4,
      durationMinutes: 120,
    },
    {
      year: "2022-07",
      title: "Julio 2022",
      date: "Julio 2022",
      description: "4 puntos · 4 preguntas",
      passPoints: 2,
      totalPoints: 4,
      durationMinutes: 120,
    },
    {
      year: "2023-01",
      title: "Enero 2023",
      date: "Enero 2023",
      description: "4 puntos · 4 preguntas",
      passPoints: 2,
      totalPoints: 4,
      durationMinutes: 120,
    },
    {
      year: "2023-07",
      title: "Julio 2023",
      date: "Julio 2023",
      description: "4.5 puntos · 5 preguntas",
      passPoints: 2.25,
      totalPoints: 4.5,
      durationMinutes: 120,
    },
    {
      year: "2024-01",
      title: "Enero 2024",
      date: "Enero 2024",
      description: "4 puntos · 4 preguntas",
      passPoints: 2,
      totalPoints: 4,
      durationMinutes: 90,
    },
    {
      year: "2024-07",
      title: "Julio 2024",
      date: "Julio 2024",
      description: "4.75 puntos · 5 preguntas",
      passPoints: 2.375,
      totalPoints: 4.75,
      durationMinutes: 120,
    },
    {
      year: "2025-01",
      title: "Enero 2025",
      date: "Enero 2025",
      description: "4 puntos · 4 preguntas",
      passPoints: 2,
      totalPoints: 4,
      durationMinutes: 90,
    },
    {
      year: "2025-07",
      title: "Julio 2025",
      date: "Julio 2025",
      description: "4 puntos · 4 preguntas",
      passPoints: 2,
      totalPoints: 4,
      durationMinutes: 120,
    },
    {
      year: "2026-01",
      title: "Enero 2026",
      date: "Enero 2026",
      description: "4.75 puntos · 5 preguntas",
      passPoints: 2.375,
      totalPoints: 4.75,
      durationMinutes: 90,
    },
  ],
};
