"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _route_page from './route-page.bones.json'
import _route_subject from './route-subject.bones.json'
import _route_practice from './route-practice.bones.json'
import _route_exam from './route-exam.bones.json'

registerBones({
  "route-page": _route_page,
  "route-subject": _route_subject,
  "route-practice": _route_practice,
  "route-exam": _route_exam,
})
