"use client"
// Auto-generated by boneyard vite plugin — do not edit
import { registerBones } from 'boneyard-js/react'

import _simulator_exam from './simulator-exam.bones.json'
import _simulator_practice from './simulator-practice.bones.json'

registerBones({
  "simulator-exam": _simulator_exam,
  "simulator-practice": _simulator_practice,
})
