"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _subject_content from './subject-content.bones.json'
import _home_subject_cards from './home-subject-cards.bones.json'

configureBoneyard({"animate":"solid","boneClass":"app-skeleton-bone"})

registerBones({
  "subject-content": _subject_content,
  "home-subject-cards": _home_subject_cards,
})
