/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as LangRouteImport } from './routes/$lang';
import { Route as SplatRouteImport } from './routes/$';
import { Route as IndexRouteImport } from './routes/index';
import { Route as LangIndexRouteImport } from './routes/$lang.index';
import { Route as LangPrivacyRouteImport } from './routes/$lang.privacy';
import { Route as LangSubjectIdRouteImport } from './routes/$lang.$subjectId';
import { Route as LangSplatRouteImport } from './routes/$lang.$';
import { Route as LangSubjectIdPracticeRouteImport } from './routes/$lang.$subjectId_.practice';
import { Route as LangSubjectIdPracticeTopicRouteImport } from './routes/$lang.$subjectId_.practice_.$topic';
import { Route as LangSubjectIdExamExamIdRouteImport } from './routes/$lang.$subjectId_.exam.$examId';

const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any);
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any);
const LangPrivacyRoute = LangPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LangRoute,
} as any);
const LangSubjectIdRoute = LangSubjectIdRouteImport.update({
  id: '/$subjectId',
  path: '/$subjectId',
  getParentRoute: () => LangRoute,
} as any);
const LangSplatRoute = LangSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => LangRoute,
} as any);
const LangSubjectIdPracticeRoute = LangSubjectIdPracticeRouteImport.update({
  id: '/$subjectId_/practice',
  path: '/$subjectId/practice',
  getParentRoute: () => LangRoute,
} as any);
const LangSubjectIdPracticeTopicRoute =
  LangSubjectIdPracticeTopicRouteImport.update({
    id: '/$subjectId_/practice_/$topic',
    path: '/$subjectId/practice/$topic',
    getParentRoute: () => LangRoute,
  } as any);
const LangSubjectIdExamExamIdRoute = LangSubjectIdExamExamIdRouteImport.update({
  id: '/$subjectId_/exam/$examId',
  path: '/$subjectId/exam/$examId',
  getParentRoute: () => LangRoute,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/$': typeof SplatRoute;
  '/$lang': typeof LangRouteWithChildren;
  '/$lang/$': typeof LangSplatRoute;
  '/$lang/$subjectId': typeof LangSubjectIdRoute;
  '/$lang/privacy': typeof LangPrivacyRoute;
  '/$lang/': typeof LangIndexRoute;
  '/$lang/$subjectId/practice': typeof LangSubjectIdPracticeRoute;
  '/$lang/$subjectId/exam/$examId': typeof LangSubjectIdExamExamIdRoute;
  '/$lang/$subjectId/practice/$topic': typeof LangSubjectIdPracticeTopicRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/$': typeof SplatRoute;
  '/$lang/$': typeof LangSplatRoute;
  '/$lang/$subjectId': typeof LangSubjectIdRoute;
  '/$lang/privacy': typeof LangPrivacyRoute;
  '/$lang': typeof LangIndexRoute;
  '/$lang/$subjectId/practice': typeof LangSubjectIdPracticeRoute;
  '/$lang/$subjectId/exam/$examId': typeof LangSubjectIdExamExamIdRoute;
  '/$lang/$subjectId/practice/$topic': typeof LangSubjectIdPracticeTopicRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/$': typeof SplatRoute;
  '/$lang': typeof LangRouteWithChildren;
  '/$lang/$': typeof LangSplatRoute;
  '/$lang/$subjectId': typeof LangSubjectIdRoute;
  '/$lang/privacy': typeof LangPrivacyRoute;
  '/$lang/': typeof LangIndexRoute;
  '/$lang/$subjectId_/practice': typeof LangSubjectIdPracticeRoute;
  '/$lang/$subjectId_/exam/$examId': typeof LangSubjectIdExamExamIdRoute;
  '/$lang/$subjectId_/practice_/$topic': typeof LangSubjectIdPracticeTopicRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/$'
    | '/$lang'
    | '/$lang/$'
    | '/$lang/$subjectId'
    | '/$lang/privacy'
    | '/$lang/'
    | '/$lang/$subjectId/practice'
    | '/$lang/$subjectId/exam/$examId'
    | '/$lang/$subjectId/practice/$topic';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/$'
    | '/$lang/$'
    | '/$lang/$subjectId'
    | '/$lang/privacy'
    | '/$lang'
    | '/$lang/$subjectId/practice'
    | '/$lang/$subjectId/exam/$examId'
    | '/$lang/$subjectId/practice/$topic';
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/$lang'
    | '/$lang/$'
    | '/$lang/$subjectId'
    | '/$lang/privacy'
    | '/$lang/'
    | '/$lang/$subjectId_/practice'
    | '/$lang/$subjectId_/exam/$examId'
    | '/$lang/$subjectId_/practice_/$topic';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  SplatRoute: typeof SplatRoute;
  LangRoute: typeof LangRouteWithChildren;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang';
      path: '/$lang';
      fullPath: '/$lang';
      preLoaderRoute: typeof LangRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/$': {
      id: '/$';
      path: '/$';
      fullPath: '/$';
      preLoaderRoute: typeof SplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/$lang/': {
      id: '/$lang/';
      path: '/';
      fullPath: '/$lang/';
      preLoaderRoute: typeof LangIndexRouteImport;
      parentRoute: typeof LangRoute;
    };
    '/$lang/privacy': {
      id: '/$lang/privacy';
      path: '/privacy';
      fullPath: '/$lang/privacy';
      preLoaderRoute: typeof LangPrivacyRouteImport;
      parentRoute: typeof LangRoute;
    };
    '/$lang/$subjectId': {
      id: '/$lang/$subjectId';
      path: '/$subjectId';
      fullPath: '/$lang/$subjectId';
      preLoaderRoute: typeof LangSubjectIdRouteImport;
      parentRoute: typeof LangRoute;
    };
    '/$lang/$': {
      id: '/$lang/$';
      path: '/$';
      fullPath: '/$lang/$';
      preLoaderRoute: typeof LangSplatRouteImport;
      parentRoute: typeof LangRoute;
    };
    '/$lang/$subjectId_/practice': {
      id: '/$lang/$subjectId_/practice';
      path: '/$subjectId/practice';
      fullPath: '/$lang/$subjectId/practice';
      preLoaderRoute: typeof LangSubjectIdPracticeRouteImport;
      parentRoute: typeof LangRoute;
    };
    '/$lang/$subjectId_/practice_/$topic': {
      id: '/$lang/$subjectId_/practice_/$topic';
      path: '/$subjectId/practice/$topic';
      fullPath: '/$lang/$subjectId/practice/$topic';
      preLoaderRoute: typeof LangSubjectIdPracticeTopicRouteImport;
      parentRoute: typeof LangRoute;
    };
    '/$lang/$subjectId_/exam/$examId': {
      id: '/$lang/$subjectId_/exam/$examId';
      path: '/$subjectId/exam/$examId';
      fullPath: '/$lang/$subjectId/exam/$examId';
      preLoaderRoute: typeof LangSubjectIdExamExamIdRouteImport;
      parentRoute: typeof LangRoute;
    };
  }
}

interface LangRouteChildren {
  LangSplatRoute: typeof LangSplatRoute;
  LangSubjectIdRoute: typeof LangSubjectIdRoute;
  LangPrivacyRoute: typeof LangPrivacyRoute;
  LangIndexRoute: typeof LangIndexRoute;
  LangSubjectIdPracticeRoute: typeof LangSubjectIdPracticeRoute;
  LangSubjectIdExamExamIdRoute: typeof LangSubjectIdExamExamIdRoute;
  LangSubjectIdPracticeTopicRoute: typeof LangSubjectIdPracticeTopicRoute;
}

const LangRouteChildren: LangRouteChildren = {
  LangSplatRoute: LangSplatRoute,
  LangSubjectIdRoute: LangSubjectIdRoute,
  LangPrivacyRoute: LangPrivacyRoute,
  LangIndexRoute: LangIndexRoute,
  LangSubjectIdPracticeRoute: LangSubjectIdPracticeRoute,
  LangSubjectIdExamExamIdRoute: LangSubjectIdExamExamIdRoute,
  LangSubjectIdPracticeTopicRoute: LangSubjectIdPracticeTopicRoute,
};

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  LangRoute: LangRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
