import type { SubjectMeta } from "../../data/types";

export const meta: SubjectMeta = {
  id: "_template",
  lastmod: "2026-07-25",
  name: "Template Subject",
  university: "Template University",
  courseCode: "TMP101",
  icon: "📝",
  contentPolicy: "community-practice",
  acknowledgments:
    "Questions provided by the Template Department. Answers by Prof. Example.",
  contentLicense:
    "Exams licensed by Example Author under the CC BY 4.0 license.",
  topics: [
    { key: "topic-1", label: "Foundations", icon: "📌", color: "blue" },
    { key: "topic-2", label: "Data and Reasoning", icon: "🔍", color: "green" },
    {
      key: "syntax-highlighting",
      label: "Code Rendering",
      icon: "💻",
      color: "purple",
    },
    {
      key: "markdown-complete",
      label: "Markdown Coverage",
      icon: "✍️",
      color: "pink",
    },
    {
      key: "lorem-ipsum",
      label: "Long-form Text",
      icon: "📖",
      color: "amber",
    },
    {
      key: "visual-assets",
      label: "Images and Solutions",
      icon: "🖼️",
      color: "cyan",
    },
    {
      key: "question-types",
      label: "Question Types",
      icon: "🧪",
      color: "orange",
    },
  ],
  megatopics: [
    {
      key: "group-a",
      label: "Group A",
      topics: ["topic-1"],
    },
    {
      key: "group-b",
      label: "Group B",
      topics: ["topic-2"],
    },
    {
      key: "rendering-tests",
      label: "Rendering Fixtures",
      topics: ["syntax-highlighting", "markdown-complete", "visual-assets"],
    },
    {
      key: "long-form",
      label: "Long-form Content",
      topics: ["lorem-ipsum"],
    },
    {
      key: "assessment",
      label: "Assessment Fixtures",
      topics: ["question-types"],
    },
  ],
  exams: [
    {
      year: "2024",
      title: "2024 Exam",
      date: "2024",
      passPoints: 35,
      totalPoints: 70,
      durationMinutes: 5,
      hasPdf: false,
    },
    {
      year: "2025-01",
      title: "January 2025",
      date: "January 2025",
      passPoints: 45,
      totalPoints: 90,
      durationMinutes: 15,
      hasPdf: false,
    },
    {
      year: "2023",
      title: "2023 Exam",
      date: "2023",
      passPoints: 0,
      totalPoints: 0,
      durationMinutes: 0,
      hasPdf: false,
      deleteRights: true,
    },
    {
      year: "code-rendering",
      title: "Code Rendering Lab",
      date: "Code rendering",
      passPoints: 35,
      totalPoints: 70,
      durationMinutes: 30,
      hasPdf: false,
    },
    {
      year: "markdown-complete",
      title: "Markdown Coverage Exam",
      date: "Markdown coverage",
      passPoints: 30,
      totalPoints: 60,
      durationMinutes: 20,
      hasPdf: false,
    },
    {
      year: "lorem-ipsum",
      title: "Long-form Reading Exam",
      date: "Long-form text",
      passPoints: 20,
      totalPoints: 40,
      durationMinutes: 25,
      hasPdf: false,
    },
    {
      year: "visual-assets",
      title: "Visual Assets Exam",
      date: "Images and solutions",
      passPoints: 25,
      totalPoints: 50,
      durationMinutes: 20,
      hasPdf: false,
    },
    {
      year: "question-types",
      title: "Question Types Exam",
      date: "Question types",
      passPoints: 15,
      totalPoints: 30,
      durationMinutes: 15,
      hasPdf: false,
    },
  ],
};

void meta;
