import type { SubjectMeta } from "../../data/types";

export const meta: SubjectMeta = {
  id: "redes",
  name: "Redes",
  university: "Universidade da Coruña",
  courseCode: "202319",
  icon: "🕸️",
  contentPolicy: "community-practice",
  acknowledgments:
    "Las preguntas y respuestas incluidas en esta plataforma son ejercicios originales creados por estudiantes anónimos a partir del temario oficial. No se reproducen exámenes oficiales, enunciados originales ni materiales docentes protegidos del profesorado o de la universidad. Si se detecta alguna coincidencia sustancial no autorizada, puede notificarse para su revisión y retirada.",
  topics: [
    {
      key: "tema-1",
      label: "Tema 1. Redes de ordenadores e Internet",
      icon: "🌐",
      color: "blue",
    },
    {
      key: "tema-2",
      label: "Tema 2. Introducción a TCP/IP",
      icon: "📚",
      color: "indigo",
    },
    {
      key: "tema-3-4",
      label: "Tema 3-4. Protocolos nivel de aplicación",
      icon: "📱",
      color: "green",
    },
    {
      key: "tema-5",
      label: "Tema 5. Protocolos de transporte UDP y TCP",
      icon: "📦",
      color: "purple",
    },
    {
      key: "tema-6",
      label: "Tema 6. Intercambio de datos TCP",
      icon: "🔄",
      color: "pink",
    },
    {
      key: "tema-7",
      label: "Tema 7. Nivel de red: protocolo IP",
      icon: "📨",
      color: "amber",
    },
    {
      key: "tema-8",
      label: "Tema 8. Enrutamiento",
      icon: "🧭",
      color: "red",
    },
    {
      key: "tema-9",
      label: "Tema 9. ICMP y fragmentación IP",
      icon: "⚠️",
      color: "cyan",
    },
    {
      key: "tema-10",
      label: "Tema 10. Protocolo IPv6",
      icon: "6️⃣",
      color: "orange",
    },
    {
      key: "tema-11",
      label: "Tema 11. TCP/IP y nivel de enlace",
      icon: "🔗",
      color: "blue",
    },
    {
      key: "tema-12",
      label: "Tema 12. Tecnologías del nivel de enlace",
      icon: "📡",
      color: "indigo",
    },
  ],
  exams: [
    {
      year: "daypo-recopilatorio-lara",
      title: "Daypo Recopilatorio (des. 2008)",
      description: "125 preguntas · 125 puntos",
      passPoints: 63,
      totalPoints: 125,
      durationMinutes: 120,
      hasPdf: false,
      daypoUrl: "https://www.daypo.com/redes-udc-examen-fic.html",
    },
    {
      year: "daypo-recopilatorio-udc",
      title: "Daypo Recopilatorio (UDC)",
      description: "298 preguntas · 298 puntos",
      passPoints: 149,
      totalPoints: 298,
      durationMinutes: 240,
      hasPdf: false,
      daypoUrl: "https://www.daypo.com/redes-udc.html",
    },
    {
      year: "2025-05",
      title: "Recopilatorio Mayo 2025",
      date: "Mayo 2025",
      description: "37 preguntas · 37 puntos",
      passPoints: 19,
      totalPoints: 37,
      durationMinutes: 120,
      hasPdf: false,
    },
  ],
};
