import type { Question } from "../../data/types";

export const questions: Question[] = [
  // ============================================================
  // TEMA 1 — REDES DE ORDENADORES E INTERNET
  // ============================================================

  {
    id: "redes_recop_q11",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-1",
    type: "mc",
    points: 1,
    question: "Un nodo intermedio implementa las...:",
    options: [
      "A. Siete capas OSI.",
      "B. Capas física y enlace de OSI.",
      "C. Capas LLC e IP de TCP/IP.",
      "D. Capas física, enlace y red de OSI.",
    ],
    correctAnswer: "d",
  },
  {
    id: "redes_recop_q14",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-1",
    type: "mc",
    points: 1,
    question:
      "¿Cuál de las siguientes afirmaciones sobre medios de transmisión es correcta?",
    options: [
      "A. Todos los medios atenúan la señal del mismo modo.",
      "B. Mayor rango de frecuencias implica mayor velocidad de transmisión.",
      "C. Todos los medios son igual de sensibles a intermodulaciones e interferencias.",
      "D. El número y distancia de repetidores necesarios es dependiente del medio físico.",
    ],
    correctAnswer: "d",
  },

  // ============================================================
  // TEMA 2 — INTRODUCCIÓN A TCP/IP
  // ============================================================

  {
    id: "redes_recop_q115",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-2",
    type: "mc",
    points: 1,
    question:
      "Supón que te conectas con tu portátil a una red a la que nunca te has conectado antes. Desde el primer momento, y sin tener que configurar nada, tienes acceso a la red como un nodo más, incluyendo salida a Internet (si la hay). ¿A qué se debe esto?",
    options: [
      "A. Tu equipo ha recibido mensajes de protocolos de enrutamiento dinámico (RIP o similares) para obtener las rutas de su tabla de routing, y ha autoconfigurado el sistema.",
      "B. Tu equipo ha encontrado un servidor DHCP que le ha enviado toda la información de configuración necesaria (dirección IP, máscara de red, router por defecto...).",
      "C. a) y b) son falsas.",
    ],
    correctAnswer: "b",
  },

  // ============================================================
  // TEMA 3-4 — PROTOCOLOS NIVEL DE APLICACIÓN
  // ============================================================

  {
    id: "redes_recop_q48",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-3-4",
    type: "mc",
    points: 1,
    question:
      "En Kerberos, ¿cuál de las siguientes afirmaciones acerca del TGT no es cierta?",
    options: [
      "A. Se envía como respuesta a una petición AS_REQUEST.",
      "B. Encapsula una clave de sesión a emplear entre el cliente y el servicio al que desea acceder.",
      "C. Está cifrado con la clave secreta del Ticket Granting Server.",
      "D. Normalmente solo es válido durante un cierto período de tiempo.",
    ],
    correctAnswer: "b",
  },
  {
    id: "redes_recop_q49",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-3-4",
    type: "mc",
    points: 1,
    question: "Un atributo LDAP...",
    options: [
      "A. Siempre tiene un único valor por entrada de directorio.",
      "B. Solo está presente en las entradas hoja (que no tienen hijos).",
      "C. Tiene asociado un tipo que determina las reglas de comparación entre distintos valores (entre otras características).",
      "D. Al contrario que las clases de objeto no está definido en el esquema de directorio.",
    ],
    correctAnswer: "c",
  },
  {
    id: "redes_recop_q53",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-3-4",
    type: "mc",
    points: 1,
    question:
      "¿En cuál de los siguientes protocolos de autenticación el contraseña se envía por la red en claro?",
    options: ["A. CHAP", "B. PAP", "C. MS-CHAP", "D. a) y c) son correctas"],
    correctAnswer: "b",
  },
  {
    id: "redes_recop_q55",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-3-4",
    type: "mc",
    points: 1,
    question:
      "¿Cuál de las siguientes afirmaciones acerca del protocolo EAP no es cierta?",
    options: [
      "A. Es un protocolo extensible que permite distintos métodos de autenticación.",
      "B. Los tres elementos que intervienen en la autenticación (cliente, NAS y servidor de autenticación) deben conocer el método de autenticación empleado.",
      "C. Los clientes precisan conocer el método de autenticación empleado.",
      "D. Se utiliza en el estándar de autenticación 802.1X.",
    ],
    correctAnswer: "b",
  },
  {
    id: "redes_recop_q56",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-3-4",
    type: "mc",
    points: 1,
    question:
      "¿Cuál de las siguientes operaciones no está definida en el protocolo LDAP?",
    options: ["A. BIND", "B. COMMIT", "C. SEARCH", "D. MODIFY"],
    correctAnswer: "b",
  },
  {
    id: "redes_recop_q57",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-3-4",
    type: "mc",
    points: 1,
    question:
      "¿Cuál de los siguientes protocolos no se utiliza en una arquitectura RSN 802.11i en redes wireless?",
    options: ["A. WEP", "B. EAP", "C. EAPOL", "D. RADIUS"],
    correctAnswer: "a",
  },
  {
    id: "redes_recop_q58",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-3-4",
    type: "mc",
    points: 1,
    question:
      '¿Qué búsqueda LDAP debemos emplear para listar los hijos directos de la entrada "ou=people,dc=udc,dc=es" que tengan el valor "Victor" en el atributo "cn"?',
    options: [
      'A. Base "dc=udc,dc=es", search scope "SUB" y filtro "cn=Victor"',
      'B. Base "ou=people,dc=udc,dc=es", search scope "BASE" y filtro "cn=Victor"',
      'C. Base "ou=people,dc=udc,dc=es", search scope "SUB" y filtro "cn=Victor*"',
      'D. Base "ou=people,dc=udc,dc=es", search scope "ONELEVEL" y filtro "cn=Victor"',
    ],
    correctAnswer: "d",
  },
  {
    id: "redes_recop_q59",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-3-4",
    type: "mc",
    points: 1,
    question:
      "Queremos controlar las descargas que realizan nuestros usuarios desde internet (vía HTTP) para detectar posibles virus, pero no tenemos la posibilidad de modificar la configuración en cada equipo cliente. ¿Cuál sería la mejor opción?",
    options: [
      "A. Bloquear el acceso HTTP con un firewall de filtrado de paquetes.",
      "B. Instalar un proxy transparente.",
      "C. Instalar un proxy dedicado, para evitar cargar en exceso el firewall principal.",
      "D. No es posible solucionar el problema sin poder cambiar la configuración en los clientes.",
    ],
    correctAnswer: "b",
  },
  {
    id: "redes_recop_q60",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-3-4",
    type: "mc",
    points: 1,
    question:
      'Supongamos que en un schema LDAP tenemos definida la clase de objeto "customPerson" con un atributo obligatorio "cn", y dos atributos opcionales: "telephoneNumber" y "postalAddress". Si tenemos una entrada de directorio en la cual el atributo "objectclass" tiene el valor "customPerson", ¿cuál de las siguientes afirmaciones no es cierta?',
    options: [
      'A. La entrada debe tener por lo menos un valor en el atributo "cn".',
      'B. La entrada podría tener atributos adicionales a los indicados en el enunciado, en caso de que el atributo "objectclass" tuviese valores adicionales al de "customPerson".',
      'C. El RDN de la entrada debe ser de la forma "cn=XXX", donde XXX sería cualquier valor que cumpla las reglas sintácticas definidas para el atributo.',
      'D. Se podrían especificar varios valores para el atributo "postalAddress", siempre y cuando en el esquema estuviese configurado como un atributo multivaluado.',
    ],
    correctAnswer: "c",
  },
  {
    id: "redes_recop_q61",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-3-4",
    type: "mc",
    points: 1,
    question: "¿Cuál de las siguientes no es una mensaxe RADIUS válida?",
    options: [
      "A. Access-Challenge",
      "B. Access-Request",
      "C. Access-Denied",
      "D. Access-Reject",
    ],
    correctAnswer: "c",
  },
  {
    id: "redes_recop_q87",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-3-4",
    type: "mc",
    points: 1,
    question: "El DNS (Domain Name System):",
    options: [
      "A. Sirve para convertir direcciones IP en nombres de máquinas.",
      "B. Sirve para convertir nombres de máquinas en direcciones IP.",
      "C. a) y b) son correctas.",
    ],
    correctAnswer: "c",
  },
  {
    id: "redes_recop_q89",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-3-4",
    type: "mc",
    points: 1,
    question: "El servicio DNS:",
    options: [
      "A. Un nombre de dominio siempre termina en un punto.",
      "B. Los nombres de dominio son únicos.",
      "C. Utiliza una estructura jerárquica donde cada nodo tiene una etiqueta que es única.",
    ],
    correctAnswer: "b",
  },
  {
    id: "redes_recop_q111",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-3-4",
    type: "mc",
    points: 1,
    question: "En un servidor DNS (Domain Name System):",
    options: [
      "A. Si un servidor primario recibe una petición que no sabe responder, acude a los servidores raíz DNS.",
      "B. Si un servidor primario recibe una petición que no sabe responder, la reenvía a un servidor secundario de la misma zona.",
      "C. Si un servidor primario recibe una petición que no sabe responder, la descarta.",
    ],
    correctAnswer: "b",
  },
  {
    id: "redes_recop_q124",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-3-4",
    type: "mc",
    points: 1,
    question: "Las peticiones inversas (de dirección IP a nombre):",
    options: [
      "A. Utilizan el dominio in-addr.arpa.",
      "B. Utilizan los mensajes de DNS request y DNS reply al revés que en las peticiones normales (de nombre a dirección IP). Se usan mensajes de reply para peticiones y mensajes de request para respuestas.",
      "C. a) y b) son falsas.",
    ],
    correctAnswer: "a",
  },

  // ============================================================
  // TEMA 5 — PROTOCOLOS DE TRANSPORTE UDP Y TCP
  // ============================================================

  {
    id: "redes_recop_q66",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-5",
    type: "mc",
    points: 1,
    question:
      "¿Cuál de las siguientes afirmaciones no es una diferencia entre UDP y TCP?",
    options: [
      "A. UDP usa puertos para identificar aplicaciones mientras que TCP utiliza sockets.",
      "B. TCP transmite tramas de manera fiable, mientras que UDP solo envía datagramas de manera no fiable.",
      "C. Checksum es opcional en UDP pero es obligatorio en TCP.",
    ],
    correctAnswer: "a",
  },
  {
    id: "redes_recop_q78",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-5",
    type: "mc",
    points: 1,
    question: "UDP es un protocolo de transporte no fiable debido a que:",
    options: [
      "A. El campo checksum de la cabecera UDP es opcional.",
      "B. Cada datagrama UDP se encapsula en un datagrama IP que a su vez proporciona un servicio de comunicación no fiable.",
      "C. No posee timeouts y retransmisiones para garantizar la fiabilidad del canal.",
    ],
    correctAnswer: "c",
  },
  {
    id: "redes_recop_q79",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-5",
    type: "mc",
    points: 1,
    question: "Cuando en UDP te intentas conectar a un puerto no existente:",
    options: [
      "A. Recibes un mensaje ICMP de Port Unreachable y se aborta la comunicación.",
      "B. Recibes un segmento de reset y se aborta la comunicación.",
      "C. Cuando han fallado todas las retransmisiones del exponential backoff obtienes un mensaje de error.",
    ],
    correctAnswer: "a",
  },
  {
    id: "redes_recop_q85",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-5",
    type: "mc",
    points: 1,
    question:
      "Si queremos establecer una conexión TCP entre las máquinas 2 y 3. El valor del MSS para la conexión será de:",
    options: [
      "A. 1460 en los dos sentidos.",
      "B. 760 en los dos sentidos.",
      "C. 1480 en un sentido y 780 en el otro sentido.",
    ],
    correctAnswer: "b",
  },
  {
    id: "redes_recop_q90",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-5",
    type: "mc",
    points: 1,
    question:
      "Para el establecimiento de conexión de la Figura 2, indica los valores de ACK que envía el servidor B (apertura pasiva) y el cliente A (apertura activa):",
    options: [
      "A. 43216 y 27891, respectivamente.",
      "B. 43215 y 27890, respectivamente.",
      "C. 43216 en ambos casos.",
    ],
    correctAnswer: "a",
  },
  {
    id: "redes_recop_q91",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-5",
    type: "mc",
    points: 1,
    question:
      'En el establecimiento simultáneo de una conexión TCP de la Figura 3, indica qué se envía en "PQT 1":',
    options: ["A. SYN 78463 y ACK 34219.", "B. SYN 78463.", "C. ACK 34219."],
    correctAnswer: "a",
  },
  {
    id: "redes_recop_q92",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-5",
    type: "mc",
    points: 1,
    question: 'El "backlog" de un servidor TCP va a determinar...',
    options: [
      "A. El nº máximo de clientes concurrentes que admite.",
      "B. El nº máximo de conexiones TCP que permite la máquina.",
      "C. El nº máximo de conexiones aceptadas por TCP y a la espera de ser aceptadas por la aplicación.",
    ],
    correctAnswer: "c",
  },
  {
    id: "redes_recop_q103",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-5",
    type: "mc",
    points: 1,
    question:
      "¿Es posible establecer una comunicación UDP con una dirección broadcast o multicast?",
    options: [
      "A. No, en ningún caso.",
      "B. Sí con una dirección de multicast, no con una dirección de broadcast.",
      "C. Sí con ambas.",
    ],
    correctAnswer: "c",
  },
  {
    id: "redes_recop_q108",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-5",
    type: "mc",
    points: 1,
    question:
      "El checksum de UDP es opcional, sin embargo ¿en qué caso es más aconsejable su utilización?",
    options: [
      "A. Si a nivel de enlace se utiliza SLIP.",
      "B. Si a nivel de enlace se utiliza Ethernet.",
      "C. No es aconsejable ni en a) ni en b).",
    ],
    correctAnswer: "a",
  },
  {
    id: "redes_recop_q112",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-5",
    type: "mc",
    points: 1,
    question:
      "En una conexión normal TCP, todos los paquetes tienen el flag ACK activado, excepto:",
    options: [
      "A. El primer paquete enviado por el servidor.",
      "B. El último paquete enviado por el cliente.",
      "C. El primer paquete enviado por el cliente.",
    ],
    correctAnswer: "c",
  },
  {
    id: "redes_recop_q113",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-5",
    type: "mc",
    points: 1,
    question: "Cuando en TCP te intentas conectar a un puerto no existente:",
    options: [
      "A. Cuando han fallado todas las retransmisiones del exponential backoff obtienes un mensaje de error.",
      "B. Recibes un mensaje ICMP de Port Unreachable y se aborta la comunicación.",
      "C. Recibes un segmento de reset y se aborta la comunicación.",
    ],
    correctAnswer: "c",
  },
  {
    id: "redes_recop_q125",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-5",
    type: "mc",
    points: 1,
    question: "UDP es un protocolo:",
    options: [
      "A. De nivel de transporte, orientado a conexión y fiable.",
      "B. De nivel de red, no orientado a conexión y no fiable.",
      "C. a) y b) son falsas.",
    ],
    correctAnswer: "c",
  },

  // ============================================================
  // TEMA 6 — INTERCAMBIO DE DATOS TCP
  // ============================================================

  {
    id: "redes_recop_q86",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-6",
    type: "mc",
    points: 1,
    question:
      "Siguiendo con la conexión, si se envía un paquete TCP de 2048 bytes desde la máquina 3:",
    options: [
      "A. Se envían 3 paquetes TCP y por lo tanto, 3 paquetes IP (pero no fragmentados).",
      "B. Se envía 1 paquete TCP, pero fragmentado en 3 paquetes IP.",
      "C. Se envían 3 paquetes TCP, pero 1 solo paquete IP.",
    ],
    correctAnswer: "a",
  },
  {
    id: "redes_recop_q88",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-6",
    type: "mc",
    points: 1,
    question: "En Telnet (implementado sobre TCP), si se pierde un paquete:",
    options: [
      "A. Es la capa de transporte la encargada de recuperarse del error.",
      "B. Es la capa de red la encargada de recuperarse del error.",
      "C. Es la capa de aplicación la encargada de recuperarse del error.",
    ],
    correctAnswer: "a",
  },
  {
    id: "redes_recop_q93",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-6",
    type: "mc",
    points: 1,
    question:
      "En el diagrama de transición de estados de TCP, ¿qué extremo pasa por el estado TIME_WAIT?",
    options: [
      "A. El extremo que realiza el cierre activo.",
      "B. Ambos extremos si se produce un cierre simultáneo.",
      "C. a) y b) son correctas.",
    ],
    correctAnswer: "c",
  },
  {
    id: "redes_recop_q94",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-6",
    type: "mc",
    points: 1,
    question:
      "En base a la Figura 4 y sabiendo que debido a un error, la máquina B se ha apagado y vuelto a encender, ¿qué respuesta recibirá la máquina A?",
    options: [
      "A. RST 25301:25301 (0), ACK 95573.",
      "B. RST 0:0 (0), ACK 95573.",
      "C. Un mensaje ICMP de Host Unreachable.",
    ],
    correctAnswer: "a",
  },
  {
    id: "redes_recop_q95",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-6",
    type: "mc",
    points: 1,
    question:
      "Un servidor TCP que no devuelve datos al cliente, generará un ACK:",
    options: [
      "A. Exactamente 200 ms después de la recepción de cada segmento de datos del cliente.",
      "B. Cada vez que se produzca un tick de reloj y existan datos sin asentir enviados por el cliente.",
      "C. a) y b) son correctas.",
    ],
    correctAnswer: "b",
  },
  {
    id: "redes_recop_q96",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-6",
    type: "mc",
    points: 1,
    question:
      "El flujo de datos interactivo (por ejemplo, el originado por un telnet) se caracteriza por que:",
    options: [
      "A. Genera una gran cantidad de paquetes de pequeño tamaño (menor de 10 bytes).",
      "B. Genera una gran cantidad de paquetes de gran tamaño (centenas de bytes).",
      "C. Genera un número reducido de paquetes, pero de gran tamaño (centenas de bytes).",
    ],
    correctAnswer: "a",
  },
  {
    id: "redes_recop_q97",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-6",
    type: "mc",
    points: 1,
    question: "En el algoritmo de ventana deslizante:",
    options: [
      'A. La ventana se "abre" producto de la liberación de espacio en el buffer de recepción.',
      'B. La ventana se "cierra" cuando se recibe un asentimiento nuevo.',
      "C. a) y b) son correctas.",
    ],
    correctAnswer: "c",
  },
  {
    id: "redes_recop_q98",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-6",
    type: "mc",
    points: 1,
    question: "La retransmisión de un segmento TCP se produce:",
    options: [
      "A. Por la recepción de 3 ACKs duplicados.",
      "B. Por haber alcanzado el valor cero el timeout de retransmisión.",
      "C. a) y b) son correctas.",
    ],
    correctAnswer: "c",
  },
  {
    id: "redes_recop_q99",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-6",
    type: "mc",
    points: 1,
    question:
      "En el justo instante en que se produce una retransmisión de un segmento TCP, observamos que ssthresh=1024 bytes y cwnd=1792 bytes. Sabiendo que el MSS es de 256 bytes, podemos deducir que:",
    options: [
      "A. La ventana de congestión crece no exponencialmente.",
      "B. La retransmisión ha sido provocada por el vencimiento del temporizador de retransmisión.",
      "C. La retransmisión ha sido provocada por la recepción de tres ACK's duplicados.",
    ],
    correctAnswer: "c",
  },
  {
    id: "redes_recop_q100",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-6",
    type: "mc",
    points: 1,
    question:
      "En una comunicación TCP, cuando un extremo cierra por completo su ventana de recepción, el otro extremo deberá esperar para transmitir nuevos datos a que:",
    options: [
      "A. Venza el temporizador de persistencia.",
      "B. Reciba un mensaje de actualización de ventana (window update).",
      "C. Se produzca cualquiera de las circunstancias anteriores.",
    ],
    correctAnswer: "c",
  },
  {
    id: "redes_recop_q114",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-6",
    type: "mc",
    points: 1,
    question: "Un host que aplique el algoritmo de Nagle:",
    options: [
      "A. Reduce el número de paquetes de pequeño tamaño que envía.",
      "B. Reduce el número de ACKs que envía.",
      "C. a) y b) son correctas.",
    ],
    correctAnswer: "a",
  },
  {
    id: "redes_recop_q116",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-6",
    type: "mc",
    points: 1,
    question:
      "Un servidor TCP que no devuelve datos al cliente, generará un ACK:",
    options: [
      "A. Como máximo, 200 ms después de la recepción de cada segmento de datos del cliente.",
      "B. Cada vez que se produzca un tick de reloj (cada 200 ms).",
      "C. No es necesario que envíe ACKs ya que no envía datos al cliente.",
    ],
    correctAnswer: "b",
  },
  {
    id: "redes_recop_q117",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-6",
    type: "mc",
    points: 1,
    question: "La ventana de congestión sirve para:",
    options: [
      "A. Tratar de evitar la congestión en los routers intermedios.",
      "B. Evitar la congestión en el receptor.",
      "C. a) y b) son correctas.",
    ],
    correctAnswer: "a",
  },
  {
    id: "redes_recop_q119",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-6",
    type: "mc",
    points: 1,
    question: "La retransmisión de un segmento TCP se produce:",
    options: [
      "A. Por la recepción de 3 ACKs duplicados.",
      "B. Por el vencimiento del temporizador de retransmisión.",
      "C. a) y b) son correctas.",
    ],
    correctAnswer: "c",
  },
  {
    id: "redes_recop_q120",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-6",
    type: "mc",
    points: 1,
    question:
      "El tiempo que espera TCP antes de retransmitir un segmento (RTO):",
    options: [
      "A. Se fija en el establecimiento de conexión y permanece constante durante todo el tiempo que dura la conexión.",
      "B. Es variable, en situaciones de congestión interesa esperar más antes de retransmitir.",
      "C. Es variable, se ajusta en cada momento al tamaño del buffer de recepción.",
    ],
    correctAnswer: "b",
  },
  {
    id: "redes_recop_q121",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-6",
    type: "mc",
    points: 1,
    question:
      "En el algoritmo de retransmisión rápida, una vez detectada la congestión por ACKs duplicados:",
    options: [
      "A. cwnd se incrementa a medida que se reciben nuevos ACKs duplicados.",
      "B. cwnd se decrementa de inmediato a 1 segmento porque el haber perdido un segmento es indicativo de congestión y no queremos sobrecargar más la red.",
      "C. a) y b) son correctas.",
    ],
    correctAnswer: "b",
  },
  {
    id: "redes_recop_q123",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-6",
    type: "mc",
    points: 1,
    repeated: true,
    question:
      "En el justo instante en que se produce una retransmisión de un segmento TCP observamos que ssthresh=1024 bytes y cwnd=1792 bytes. Sabiendo que el MSS es de 256 bytes, podemos deducir que:",
    options: [
      "A. La ventana de congestión crece no exponencialmente.",
      "B. La retransmisión ha sido provocada por el vencimiento del temporizador de transmisión.",
      "C. La retransmisión ha sido provocada por la recepción de tres ACKs duplicados.",
    ],
    correctAnswer: "b",
  },

  // ============================================================
  // TEMA 7 — NIVEL DE RED: PROTOCOLO IP
  // ============================================================

  {
    id: "redes_recop_q54",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-7",
    type: "mc",
    points: 1,
    question:
      "¿Por qué opción debemos decantarnos si queremos permitir el acceso desde internet a un servidor de correo y otro web, situados en una DMZ detrás de un firewall, pero solo tenemos una IP pública?",
    options: [
      "A. Solo es posible, usando NAT, si los servidores están desplegados en máquinas virtuales (como vmware) en la misma máquina física con la red configurada con bridge.",
      "B. Podemos utilizar PAT (port forwarding) en el firewall para mapear ambos servidores, que contarán con IPs privadas.",
      "C. No es posible, tenemos que tener IPs públicas para cada uno de los servidores.",
      "D. Debemos configurar las tres máquinas con el mismo enderezo IP.",
    ],
    correctAnswer: "b",
  },
  {
    id: "redes_recop_q69",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-7",
    type: "mc",
    points: 1,
    question:
      "Un administrador de red con dos direcciones públicas de Internet conecta una red con 20 nodos a Internet utilizando NAT dinámico. ¿Cuál será el número máximo de conexiones simultáneas de esas máquinas con Internet?",
    options: [
      "A. 2",
      "B. Tantas como pares (IP válida propia, nº puerto propio), (IP válida externa, nº puerto externo) se puedan diferenciar.",
      "C. 20",
    ],
    correctAnswer: "b",
  },
  {
    id: "redes_recop_q70",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-7",
    type: "mc",
    points: 1,
    question:
      "Para establecer redes privadas en Internet utilizando NAT, el router de entrada/salida de la red privada:",
    options: [
      "A. Debe modificar las direcciones de destino de los datagramas entrantes para convertirlas a direcciones reales de la red privada.",
      "B. Debe modificar las direcciones de origen privadas de los datagramas salientes para convertirlas, según un procedimiento establecido por NAT, a direcciones válidas en Internet.",
      "C. a) y b) son ciertas.",
    ],
    correctAnswer: "c",
  },
  {
    id: "redes_recop_q71",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-7",
    type: "mc",
    points: 1,
    question: "¿Cómo puede una máquina conocer la máscara de su subred?",
    options: [
      "A. Todas las máquinas conocen su máscara de subred y no precisan hacer la consulta.",
      "B. Introduciendo en la red un mensaje broadcast ICMP de tipo 17.",
      "C. Mediante un broadcast a todas las máquinas de su subred y un cálculo posterior de la máscara a partir de los mensajes recibidos en contestación al broadcast.",
    ],
    correctAnswer: "b",
  },
  {
    id: "redes_recop_q73",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-7",
    type: "mc",
    points: 1,
    question: "El tamaño máximo de datagrama IP viene determinado por:",
    options: [
      "A. Los niveles de transporte y de aplicación.",
      "B. El tamaño del buffer IP del sistema operativo.",
      "C. El campo de longitud de 16 bits de la primera palabra de la cabecera IP.",
    ],
    correctAnswer: "c",
  },
  {
    id: "redes_recop_q77",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-7",
    type: "mc",
    points: 1,
    question: "La función del campo TTL en IP es:",
    options: [
      "A. Determinar el número máximo de routers que puede atravesar el datagrama.",
      "B. Almacenar el tiempo de transmisión del datagrama.",
      "C. Establecer la ruta fija que debe seguir el datagrama.",
    ],
    correctAnswer: "a",
  },
  {
    id: "redes_recop_q101",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-7",
    type: "mc",
    points: 1,
    question: "Las direcciones de clase A, B y C se diferencian en:",
    options: [
      "A. El tamaño del identificador de red y del identificador de host.",
      "B. Las clase A no permiten subnetting.",
      "C. Las clase A tienen una longitud de 31 bits, las clase B de 30 bits y las clase C de 29 bits.",
    ],
    correctAnswer: "a",
  },
  {
    id: "redes_recop_q104",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-7",
    type: "mc",
    points: 1,
    question:
      "La interfaz de loopback evita que determinados paquetes salgan a la red. ¿Cuáles?",
    options: [
      "A. Paquetes cuya dirección IP de destino sea la de la propia máquina.",
      "B. Paquetes cuya dirección IP de destino sea una dirección de broadcast.",
      "C. a) y b) son correctas.",
    ],
    correctAnswer: "a",
  },
  {
    id: "redes_recop_q107",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-7",
    type: "mc",
    points: 1,
    question: "CIDR permite:",
    options: [
      "A. Que varias máquinas compartan la misma dirección IP.",
      "B. Configurar dinámicamente la dirección IP, router por defecto y otros parámetros de un nodo.",
      "C. Disminuir el tamaño de las tablas de rutas, especialmente de los routers de los niveles altos de la jerarquía de Internet.",
    ],
    correctAnswer: "c",
  },
  {
    id: "redes_recop_q109",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-7",
    type: "mc",
    points: 1,
    question: "NAT:",
    options: [
      "A. Es una técnica orientada a disminuir el número de entradas en las tablas de enrutamiento.",
      "B. Es una técnica que permite a las aplicaciones ver varias redes como si fuesen una sola.",
      "C. Permite que varios nodos de una red compartan la misma dirección IP pública en sus comunicaciones con redes externas.",
    ],
    correctAnswer: "c",
  },
  {
    id: "redes_recop_q118",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-7",
    type: "mc",
    points: 1,
    question: "El MTU (Maximum Transmission Unit) es:",
    options: [
      "A. El número máximo de bytes de datos que puede transmitir el nivel de enlace.",
      "B. El número máximo de bytes de datos que se puede transmitir en un datagrama IP.",
      "C. El número máximo de bytes de datos que se puede transmitir en un segmento TCP.",
    ],
    correctAnswer: "b",
  },
  {
    id: "redes_recop_q122",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-7",
    type: "mc",
    points: 1,
    question: "El campo TTL (Time To Live) de la cabecera IP:",
    options: [
      "A. No se utiliza en la actualidad.",
      "B. Evita que un paquete IP circule indefinidamente por la red y tiene sentido utilizarlo tanto con UDP como con TCP.",
      "C. Evita que un paquete IP circule indefinidamente por la red, pero solo tiene sentido utilizarlo en comunicaciones con UDP.",
    ],
    correctAnswer: "b",
  },

  // ============================================================
  // TEMA 8 — ENRUTAMIENTO
  // ============================================================

  {
    id: "redes_recop_q68",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-8",
    type: "mc",
    points: 1,
    question:
      "Un router da de baja un grupo multicast en una de sus interfaces cuando:",
    options: [
      "A. Un nodo informa al router de que ya no pertenece a ese grupo de multicast.",
      "B. Recibe un error por haber encaminado tráfico de multicast a través de esa interfaz.",
      "C. El router no recibe ninguna respuesta de los nodos conectados a través de esa interfaz a la pregunta de quién está activado en ese grupo de multicast.",
    ],
    correctAnswer: "c",
  },
  {
    id: "redes_recop_q72",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-8",
    type: "mc",
    points: 1,
    question: "RIP utiliza como base para establecer rutas entre routers:",
    options: [
      "A. La distancia o número de saltos para llegar al destino.",
      "B. El ancho de banda del enlace.",
      "C. El flag de prioridad de ruta establecido por el administrador.",
    ],
    correctAnswer: "a",
  },
  {
    id: "redes_recop_q74",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-8",
    type: "mc",
    points: 1,
    question:
      "El orden de consulta de las entradas de una tabla de encaminamiento determina que:",
    options: [
      "A. Se consulten por su orden en la tabla.",
      "B. Primero se consulten por orden, de arriba a abajo, las entradas con flag H.",
      "C. Primero se consulten por orden, de arriba a abajo, las entradas con flag G.",
    ],
    correctAnswer: "b",
  },
  {
    id: "redes_recop_q76",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-8",
    type: "mc",
    points: 1,
    question: '¿Qué routers no tienen entrada "default"?',
    options: [
      "A. Ninguno.",
      "B. Los routers hoja, es decir, los más bajos en la jerarquía de Internet.",
      "C. Los routers TLD, es decir, los más altos en la jerarquía de Internet.",
    ],
    correctAnswer: "c",
  },
  {
    id: "redes_recop_q106",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-8",
    type: "mc",
    points: 1,
    question:
      "Si el nivel IP de una máquina está configurado para actuar como router y recibe un paquete cuyo destino no es esa máquina:",
    options: [
      "A. Lo enruta de acuerdo a su propia tabla de rutas.",
      "B. Lo descarta y genera un mensaje de error ICMP.",
      "C. Lo descarta sin generar ningún mensaje de error.",
    ],
    correctAnswer: "a",
  },
  {
    id: "redes_recop_q110",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-8",
    type: "mc",
    points: 1,
    question:
      "Un router R2 recibe un mensaje RIP proveniente de un router R1 al que está conectado directamente a través de uno de sus interfaces. En dicho mensaje R1 indica la métrica 1 para la red N1. ¿Qué métrica asignará R2 para N1 en su tabla RIP?",
    options: ["A. 1", "B. 2", "C. 3"],
    correctAnswer: "b",
  },

  // ============================================================
  // TEMA 9 — ICMP Y FRAGMENTACIÓN IP
  // ============================================================

  {
    id: "redes_recop_q80",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-9",
    type: "mc",
    points: 1,
    question: "En la fragmentación IP:",
    options: [
      "A. Todos los fragmentos siguen la misma ruta.",
      "B. El reensamblaje de los fragmentos se produce en el último router que éstos atraviesan antes de llegar al host destino.",
      "C. La fragmentación se puede producir en el host emisor y en cualquier router intermedio.",
    ],
    correctAnswer: "c",
  },
  {
    id: "redes_recop_q81",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-9",
    type: "mc",
    points: 1,
    question:
      "Al enviar 2048 bytes de datos UDP (sin incluir la cabecera UDP) desde la máquina 3 a la máquina 1, por el segmento C circulan:",
    options: [
      "A. 2 fragmentos IP de 1480 y 568 bytes.",
      "B. 2 fragmentos IP: de 1500 y 596 bytes.",
      "C. 2 fragmentos IP: de 1500 y 604 bytes.",
    ],
    correctAnswer: "b",
  },
  {
    id: "redes_recop_q82",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-9",
    type: "mc",
    points: 1,
    question:
      "Al enviar 2048 bytes de datos UDP (sin incluir la cabecera UDP) desde la máquina 3 a la máquina 1, por el segmento A circulan:",
    options: [
      "A. 3 fragmentos IP: 2 de 800 bytes y 1 de 504 bytes.",
      "B. 3 fragmentos IP: de 796, 724 y 596 bytes, respectivamente.",
      "C. 2 fragmentos IP: de 1700 y 396 bytes.",
    ],
    correctAnswer: "b",
  },
  {
    id: "redes_recop_q83",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-9",
    type: "mc",
    points: 1,
    question:
      "¿Qué offset (en decimal) se almacenará en el último fragmento que circule por el segmento A?",
    options: ["A. 1480", "B. 1472", "C. 1500"],
    correctAnswer: "a",
  },
  {
    id: "redes_recop_q84",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-9",
    type: "mc",
    points: 1,
    question: "¿Y cuántos fragmentos circularán por el segmento B?",
    options: ["A. 2", "B. 1", "C. 3"],
    correctAnswer: "c",
  },
  {
    id: "redes_recop_q105",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-9",
    type: "mc",
    points: 1,
    question: "ICMP es un protocolo cuya principal función es:",
    options: [
      "A. Gestionar grupos de multicast.",
      "B. Comunicar mensajes de error y otras condiciones especiales.",
      "C. a) y b) son falsas.",
    ],
    correctAnswer: "b",
  },

  // ============================================================
  // TEMA 11 — TCP/IP Y NIVEL DE ENLACE
  // ============================================================

  {
    id: "redes_recop_q16",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-11",
    type: "mc",
    points: 1,
    question:
      "¿Por qué se incorpora un campo de relleno en la trama MAC 802.3?",
    options: [
      "A. Para aumentar la eficiencia del protocolo.",
      "B. Para construir siempre tramas del mismo tamaño.",
      "C. Para el correcto funcionamiento de la técnica de detección de colisiones.",
      "D. Para conseguir tramas lo suficientemente largas que puedan ser detectadas por todas las estaciones del bus al mismo tiempo.",
    ],
    correctAnswer: "c",
  },
  {
    id: "redes_recop_q17",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-11",
    type: "mc",
    points: 1,
    question:
      "Cuando una estación con MAC 802.3 realiza un direccionamiento multicast, ¿cuántas tramas emite?",
    options: [
      "A. Una por cada estación que tiene correspondencia con la dirección de multicast.",
      "B. Envía una al router o gateway y este dispositivo se encarga de distribuirla a todas las estaciones que se correspondan con la dirección de multicast.",
      "C. Si existe un bridge dos, en caso contrario una sola.",
      "D. Una sola trama que es copiada por todas las estaciones que tienen correspondencia con esa dirección de multicast.",
    ],
    correctAnswer: "d",
  },
  {
    id: "redes_recop_q22",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-11",
    type: "mc",
    points: 1,
    question: "La técnica de VLANs permite...",
    options: [
      "A. Definir dominios de colisión lógicos.",
      "B. Definir dominios de emisión lógicos.",
      "C. Aislar el protocolo de red.",
      "D. Aumentar el ancho de banda.",
    ],
    correctAnswer: "b",
  },
  {
    id: "redes_recop_q23",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-11",
    type: "mc",
    points: 1,
    question:
      "¿Cuál de los siguientes tipos de definición de VLANs presentará una mejor eficiencia en el tratamiento de los paquetes remitidos por las estaciones?",
    options: [
      "A. Layer 1 o por Puerto.",
      "B. Layer 2 o por MAC.",
      "C. Layer 3.",
      "D. Layer 4.",
    ],
    correctAnswer: "a",
  },
  {
    id: "redes_recop_q24",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-11",
    type: "mc",
    points: 1,
    question:
      "Suponiendo que el código de fabricante de Sun Microsystems en las MAC es 08:00:20, ¿cuál de las siguientes direcciones es una dirección de multicast?",
    options: [
      "A. 08:00:20:00:00:01",
      "B. 08:00:2l:00:00.0l",
      "C. 09:os:20:0s:00:o1",
      "D. 88:00:20:00:00:01",
    ],
    correctAnswer: "c",
  },
  {
    id: "redes_recop_q28",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-11",
    type: "mc",
    points: 1,
    question:
      "¿Cuál de los siguientes equipos puede actuar de firewall en una red?",
    options: ["A. Repetidor.", "B. Bridge.", "C. Router.", "D. Conmutador."],
    correctAnswer: "c",
  },
  {
    id: "redes_recop_q29",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-11",
    type: "mc",
    points: 1,
    question:
      "¿Cuál de los siguientes equipos puede aislar el protocolo MAC entre dos segmentos de red?",
    options: ["A. Repetidor.", "B. Bridge.", "C. Router.", "D. Conmutador."],
    correctAnswer: "c",
  },
  {
    id: "redes_recop_q30",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-11",
    type: "mc",
    points: 1,
    question:
      "¿Qué equipo necesitaremos para interconectar una red IP y una red IPX?",
    options: ["A. Repetidor.", "B. Bridge.", "C. Router.", "D. Conmutador."],
    correctAnswer: "c",
  },
  {
    id: "redes_recop_q50",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-11",
    type: "mc",
    points: 1,
    question:
      'Tenemos una red con un único firewall con tres interfaces de red, que corresponden a las redes WAN, LAN y DMZ. El firewall, que es del tipo "Stateful Packet Filtering" tiene configuradas las siguientes reglas, en el orden indicado:\n1. Permitir paquetes entrantes desde la red WAN, con destino el servidor web (en la DMZ), al puerto 80/TCP y estado "nueva conexión"\n2. Denegar paquetes procedentes de la red WAN\n3. Permitir cualquier paquete saliente desde la red LAN\n4. Denegar el resto de paquetes\n¿Qué cambios nos permitirían consultar por HTTP, desde la red WAN, las páginas web alojadas en el servidor web de la DMZ?',
    options: [
      "A. Situar el servidor web en la LAN en lugar de en la DMZ.",
      "B. No es necesario añadir ninguna regla, la configuración actual ya permite el acceso requerido.",
      "C. Una regla para permitir todo después de la 3ª.",
      "D. Ninguna de las anteriores es correcta.",
    ],
    correctAnswer: "d",
  },
  {
    id: "redes_recop_q51",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-11",
    type: "mc",
    points: 1,
    question:
      "¿Cuál de las siguientes afirmaciones referidas a la configuración indicada en la pregunta anterior es cierta?",
    options: [
      "A. Los equipos de la LAN pueden navegar por internet.",
      "B. Los equipos de la LAN no pueden consultar las páginas alojadas en el servidor web de la DMZ.",
      "C. Los equipos de la DMZ tienen acceso HTTP a máquinas en la red WAN.",
      "D. Si la 4ª regla estuviese en primer lugar, no sería posible la comunicación entre dos equipos de la LAN.",
    ],
    correctAnswer: "b",
  },
  {
    id: "redes_recop_q52",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-11",
    type: "mc",
    points: 1,
    question:
      "¿Cuál de las siguientes situaciones puede ser controlada por un firewall de filtrado de paquetes básico (sin estado)?",
    options: [
      "A. Bloquear paquetes que inicien nuevas conexiones TCP.",
      "B. Bloquear el acceso desde ciertas IPs.",
      "C. Bloquear el acceso a paquetes TCP que no inicien nuevas conexiones.",
      "D. Las tres son correctas.",
    ],
    correctAnswer: "d",
  },
  {
    id: "redes_recop_q62",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-11",
    type: "mc",
    points: 1,
    question:
      "¿Cuál de las siguientes es una limitación de los firewalls de filtrado de paquetes básicos (sin estado)?",
    options: [
      "A. Su rendimiento es muy limitado.",
      "B. Son incapaces de distinguir si un paquete pertenece a una conexión ya establecida.",
      "C. Solo pueden bloquear tráfico TCP o UDP, teniendo problemas con otro tipo de tráfico (ej: ICMP).",
      "D. No son capaces de bloquear tráfico procedente de la red interna.",
    ],
    correctAnswer: "b",
  },
  {
    id: "redes_recop_q63",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-11",
    type: "mc",
    points: 1,
    question:
      "Tenemos una red con dos firewalls, un exterior (boundary router, filtrado de paquetes básico) y un principal (stateful packet filtering). Entre ambos se sitúa la DMZ externa. Detrás del firewall principal tenemos la red interna (LAN), y una DMZ interna de tipo Service Leg. ¿Cuál de los siguientes sería el lugar más apropiado para situar un servidor HTTP público con un nivel de tráfico relativamente elevado?",
    options: [
      "A. En la DMZ externa, para mantener el servidor protegido por el firewall exterior, al tiempo que el firewall interno protege las otras redes, más sensibles.",
      "B. En la DMZ interna, ya que las DMZ de tipo Service Leg son las más apropiadas para manejar altos volúmenes de carga.",
      "C. En la LAN, ya que los servidores públicos requieren de especial protección, y estar tras 2 firewalls es lo más adecuado en este caso.",
      "D. En la red exterior, ya que los servidores públicos, por definición, no deben estar detrás de un firewall.",
    ],
    correctAnswer: "a",
  },
  {
    id: "redes_recop_q64",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-11",
    type: "mc",
    points: 1,
    question:
      'Se creó un script con nombre iptables.sh (con permisos 744) bajo /etc/init.d y se ejecutó el comando "update-rc.d iptables.sh defaults". Teniendo en cuenta que el script no tiene errores:',
    options: [
      "A. La configuración es correcta y no tiene ningún problema.",
      "B. En el modo monousuario no se levanta el firewall (hay un problema de seguridad en la configuración, ya que en este nivel se levantan servicios de red).",
      "C. Es necesario colocar el script en el directorio /etc/network/if-pre-up.d y cualquier otra solución sería errónea.",
      "D. Al emplear defaults como opción ya se crean enlaces en todos los niveles en los que se levantan servicios de red.",
    ],
    correctAnswer: "b",
  },
  {
    id: "redes_recop_q65",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-11",
    type: "mc",
    points: 1,
    question: "ARP es un protocolo para:",
    options: [
      "A. Descubrir si hay un router IP nuevo en la red.",
      "B. Comprobar si una red Ethernet está funcionando.",
      "C. Hacer corresponder una dirección IP con una dirección Ethernet.",
    ],
    correctAnswer: "c",
  },
  {
    id: "redes_recop_q67",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-11",
    type: "mc",
    points: 1,
    question:
      "La dirección a activar en un nodo Ethernet para indicar la pertenencia al grupo multicast 01110111001001010101001 es:",
    options: [
      "A. 01:00:5e:3b:92:a9",
      "B. 01:00:5e:88:25:a9",
      "C. 00:00:5e:88:25:a9",
    ],
    correctAnswer: "a",
  },
  {
    id: "redes_recop_q75",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-11",
    type: "mc",
    points: 1,
    question:
      "La dirección de broadcast en Ethernet a una red distinta de la de la máquina que efectúa el broadcast:",
    options: [
      "A. Utiliza como dirección de destino la dirección de la red destino con todo unos en el campo de dirección de máquina.",
      "B. Utiliza como dirección de destino la dirección de broadcast de la red destino.",
      "C. No es posible.",
    ],
    correctAnswer: "c",
  },
  {
    id: "redes_recop_q102",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-11",
    type: "mc",
    points: 1,
    question: "¿Cuándo una máquina envía un ARP Request?",
    options: [
      "A. Cuando quiere averiguar una dirección IP de otra máquina o la suya propia en el proceso de arranque.",
      "B. Cuando quiere averiguar la dirección Ethernet de una máquina.",
      "C. a) y b) son correctas.",
    ],
    correctAnswer: "b",
  },

  // ============================================================
  // TEMA 12 — TECNOLOGÍAS DEL NIVEL DE ENLACE
  // ============================================================

  {
    id: "redes_recop_q1",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-12",
    type: "mc",
    points: 1,
    question:
      "¿Cuál de las siguientes modulaciones no se utiliza en redes WIFI?",
    options: ["A. FHSS", "B. OFDM", "C. OMTF", "D. DSSS"],
    correctAnswer: "c",
  },
  {
    id: "redes_recop_q2",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-12",
    type: "mc",
    points: 1,
    question: "¿Para qué sirven las antenas de diversidad en WIFI?",
    options: [
      "A. Para aumentar el número de canales por parte del punto de acceso",
      "B. Debido a los problemas derivados de las interferencias por el rebote de la señal en obstáculos",
      "C. Para poder transmitir con mayor potencia la señal y de este modo alcanzar mayores distancias",
      "D. Estas antenas no se utilizan en este tipo de redes",
    ],
    correctAnswer: "b",
  },
  {
    id: "redes_recop_q3",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-12",
    type: "mc",
    points: 1,
    question: "¿Por qué no se utiliza CSMA/CD en redes WIFI?",
    options: [
      "A. No es eficiente en este tipo de redes.",
      "B. Cuando una estación comienza a transmitir no puede detectar si hay otras emisiones en marcha.",
      "C. Debido a la potencia con la que se emite en este tipo de redes.",
      "D. No se pueden usar protocolos de control de errores en este tipo de redes.",
    ],
    correctAnswer: "b",
  },
  {
    id: "redes_recop_q4",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-12",
    type: "mc",
    points: 1,
    question:
      "¿Cuál es la finalidad de utilizar fragmentación en redes inalámbricas?",
    options: [
      "A. Conseguir una mayor eficiencia en la transmisión de datos cuando la distancia con el punto de acceso es elevada.",
      "B. Disminuir los efectos de las interferencias en entornos con mucho ruido.",
      "C. Adaptar al medio el tamaño del paquete al requerido por los niveles inferiores TCP/IP.",
      "D. No se realiza fragmentación en este tipo de redes.",
    ],
    correctAnswer: "b",
  },
  {
    id: "redes_recop_q5",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-12",
    type: "mc",
    points: 1,
    question:
      "En redes WIFI se utilizan las señales RTS (Request To Send) y CTS (Clear To Send) para...",
    options: [
      "A. Mejorar el rendimiento de la red en entornos ruidosos y con problemas de multitrayectoria.",
      "B. Avisar al resto de estaciones de que una está transmitiendo cuando no existe alcance directo entre todas.",
      "C. Impedir la comunicación entre dos estaciones cuyo radio de cobertura no es el adecuado.",
      "D. No se utilizan este tipo de señales en redes WIFI.",
    ],
    correctAnswer: "b",
  },
  {
    id: "redes_recop_q6",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-12",
    type: "mc",
    points: 1,
    question:
      "¿Cuál es la banda de funcionamiento de OFDM (Orthogonal Frequency Division Multiplexing) cuando se utiliza en redes WIFI 802.11?",
    options: ["A. 850-950 nm", "B. 5 GHz", "C. 2,4 GHz", "D. 1 MHz"],
    correctAnswer: "b",
  },
  {
    id: "redes_recop_q7",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-12",
    type: "mc",
    points: 1,
    question: "¿Con qué técnica se necesita mayor potencia de emisión en WIFI?",
    options: [
      "A. Direct Sequence",
      "B. Frequency Hopping",
      "C. En las dos técnicas anteriores se necesita la misma potencia de emisión.",
      "D. La potencia de emisión siempre es menor de 1 mW independientemente del tipo de técnica utilizada.",
    ],
    correctAnswer: "b",
  },
  {
    id: "redes_recop_q8",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-12",
    type: "mc",
    points: 1,
    question: "¿Contempla 802.11 la itinerancia o el roaming de estaciones?",
    options: [
      "A. Sí, se incorpora al estándar directamente.",
      "B. Sí, pero a través de mecanismos propietarios como el Inter-Access Point Protocol.",
      "C. Sí, pero no es posible mantener la conexión con el punto de acceso.",
      "D. No, en ningún caso es posible llevar a cabo esta funcionalidad en redes Wifi.",
    ],
    correctAnswer: "b",
  },
  {
    id: "redes_recop_q9",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-12",
    type: "mc",
    points: 1,
    question:
      "En una arquitectura Bluetooth, ¿quién se encarga de fijar el patrón de salto de frecuencias?",
    options: [
      "A. El punto de acceso.",
      "B. La estación que actúa de maestro.",
      "C. La estación que inicia la conexión.",
      "D. En Bluetooth no se utiliza salto de frecuencias.",
    ],
    correctAnswer: "b",
  },
  {
    id: "redes_recop_q10",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-12",
    type: "mc",
    points: 1,
    question:
      "El protocolo HDLC garantiza una conexión libre de errores entre:",
    options: [
      "A. Extremos finales.",
      "B. Enlaces punto a punto.",
      "C. No puede garantizar la ausencia de errores.",
      "D. Estaciones finales conectadas vía radio.",
    ],
    correctAnswer: "b",
  },
  {
    id: "redes_recop_q12",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-12",
    type: "mc",
    points: 1,
    question:
      "¿Con qué tipo de tramas se realiza el establecimiento de la conexión en HDLC?",
    options: [
      "A. Información",
      "B. Supervisión",
      "C. No numeradas",
      "D. HDLC no realiza establecimiento de la conexión.",
    ],
    correctAnswer: "c",
  },
  {
    id: "redes_recop_q13",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-12",
    type: "mc",
    points: 1,
    question: "ADSL es una tecnología utilizada en...",
    options: [
      "A. Red de Distribución",
      "B. Red de Usuario",
      "C. Red de Acceso",
      "D. Red Troncal",
    ],
    correctAnswer: "c",
  },
  {
    id: "redes_recop_q15",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-12",
    type: "mc",
    points: 1,
    question:
      "¿En qué situación Token Ring es más eficiente que Ethernet en el acceso al medio?",
    options: [
      "A. Gran número de estaciones con transmisiones cortas.",
      "B. Pocas estaciones con transmisiones cortas.",
      "C. Pocas estaciones con transmisiones largas.",
      "D. En ningún caso.",
    ],
    correctAnswer: "a",
  },
  {
    id: "redes_recop_q18",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-12",
    type: "mc",
    points: 1,
    question:
      "¿Cuál es el principal motivo de que en la técnica IEEE 802.5 sea la estación transmisora la que elimine su trama del anillo?",
    options: [
      "A. Por motivos de eficiencia ya que en general se conseguirán tramas más largas.",
      "B. Por motivos de control de flujo ya que la estación transmisora puede abortar la transmisión con mayor rapidez que si tiene que esperar a la indicación de la receptora.",
      "C. Por motivos de control de errores y direccionamiento múltiple.",
      "D. No existe ningún motivo, se trata de una decisión de diseño.",
    ],
    correctAnswer: "c",
  },
  {
    id: "redes_recop_q19",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-12",
    type: "mc",
    points: 1,
    question:
      "En la técnica 10-Base-T, para que una estación pueda detectar colisión de su propia trama, la duración de su transmisión tendrá:",
    options: [
      "A. Una longitud igual al retardo de propagación.",
      "B. Una longitud de al menos dos veces el retardo de propagación.",
      "C. Una longitud de al menos cuatro veces el retardo de propagación.",
      "D. La colisión se ve reflejada en todo el bus por lo que todas las estaciones se enteran de la ocurrencia de la colisión.",
    ],
    correctAnswer: "b",
  },
  {
    id: "redes_recop_q20",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-12",
    type: "mc",
    points: 1,
    question:
      "En la técnica 10-Base-2 el mínimo desaprovechamiento teórico derivado de una colisión cuando el retardo de propagación es 1 msg.",
    options: [
      "A. 0,01 Mbps.",
      "B. 0,002 Mbps.",
      "C. 0,02 Mbps.",
      "D. 0,001 Mbps.",
    ],
    correctAnswer: "c",
  },
  {
    id: "redes_recop_q21",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-12",
    type: "mc",
    points: 1,
    question:
      "En FDDI el tiempo de posesión de testigo se utiliza como temporizador para...",
    options: [
      "A. Detectar si el testigo ha llegado retrasado.",
      "B. Transmitir tramas asíncronas cuando la estación ha capturado un testigo pronto.",
      "C. Transmitir tramas síncronas.",
      "D. No se utiliza este tiempo en FDDI.",
    ],
    correctAnswer: "b",
  },
  {
    id: "redes_recop_q25",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-12",
    type: "mc",
    points: 1,
    question:
      "Si el modo de funcionamiento de nuestra LAN se basa en pocas estaciones realizando transmisiones esporádicas pero largas, ¿qué tecnología es más adecuada?",
    options: ["A. Ethernet.", "B. FDDI.", "C. Token Ring.", "D. LANE."],
    correctAnswer: "a",
  },
  {
    id: "redes_recop_q26",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-12",
    type: "mc",
    points: 1,
    question: "En FDDI, ¿qué quiere decir que el testigo ha llegado pronto?",
    options: [
      "A. No se ha consumido todo el tiempo de posesión de testigo (THT).",
      "B. El contador de rotación del testigo (TRT) ha llegado a cero varias veces.",
      "C. El contador de rotación del testigo (TRT) no ha llegado a cero y el contador de retrasos (LC) está en cero.",
      "D. El contador de retrasos (LC) no es superior a uno.",
    ],
    correctAnswer: "c",
  },
  {
    id: "redes_recop_q27",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-12",
    type: "mc",
    points: 1,
    question: "¿Cuál de las siguientes funciones NO realiza un bridge?",
    options: [
      "A. Aislar tráfico basándose en la dirección MAC.",
      "B. Aprender la localización de los nodos observando el tráfico.",
      "C. Aislar errores MAC.",
      "D. Balanceo de tráfico entre rutas redundantes de forma dinámica.",
    ],
    correctAnswer: "d",
  },
  {
    id: "redes_recop_q31",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-12",
    type: "mc",
    points: 1,
    question:
      "¿Por qué representan un problema las bobinas de carga en los bucles de abonado con ADSL?",
    options: [
      "A. Atenúan la señal en altas frecuencias de manera uniforme.",
      "B. No amplifican la señal de manera uniforme en todas las frecuencias.",
      "C. Aumentan la longitud del bucle de abonado y por tanto la capacidad de transmisión de este.",
      "D. Incrementan la potencia de transmisión de la señal.",
    ],
    correctAnswer: "b",
  },
  {
    id: "redes_recop_q32",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-12",
    type: "mc",
    points: 1,
    question:
      "La principal diferencia entre el acceso mediante ADSL y el ofrecido por las redes de cable es...",
    options: [
      "A. ADSL es un acceso compartido.",
      "B. ADSL es un acceso conmutado.",
      "C. ADSL presenta mayor velocidad de acceso.",
      "D. ADSL utiliza el cable coaxial para llegar al nodo de acceso.",
    ],
    correctAnswer: "b",
  },
  {
    id: "redes_recop_q33",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-12",
    type: "mc",
    points: 1,
    question: "Las principales características de ADSL son...",
    options: [
      "A. Digitalización del bucle de abonado, velocidad asimétrica y modulación QPSK.",
      "B. Digitalización del bucle de abonado, velocidad simétrica y modulación QPSK.",
      "C. Digitalización del bucle de abonado, velocidad asimétrica y modulación DMT.",
      "D. Digitalización del bucle de abonado, velocidad simétrica y modulación DMT.",
    ],
    correctAnswer: "c",
  },
  {
    id: "redes_recop_q34",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-12",
    type: "mc",
    points: 1,
    question: "La modulación DMT se basa en la utilización de...",
    options: [
      "A. División del espectro de frecuencias en subcanales y utilización de la misma portadora en cada subcanal.",
      "B. Utilización de diferentes niveles de modulación en cada frecuencia de la señal.",
      "C. Utilización de frecuencias por encima de los 2 MHz en bucles de abonado.",
      "D. División del espectro de frecuencias en subcanales y utilización de portadoras diferentes en cada subcanal.",
    ],
    correctAnswer: "d",
  },
  {
    id: "redes_recop_q35",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-12",
    type: "mc",
    points: 1,
    question:
      "¿Cuál de las siguientes afirmaciones NO es una limitación de HDSL?",
    options: [
      "A. Utilización de repetidores para distancias mayores de 3,7 Km.",
      "B. Gran cantidad de implementaciones propietarias.",
      "C. Necesidad de utilización de más de un bucle de abonado.",
      "D. Utilización de un rango de frecuencias superior al tradicional en el transporte de señales E1.",
    ],
    correctAnswer: "d",
  },
  {
    id: "redes_recop_q36",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-12",
    type: "mc",
    points: 1,
    question: "La principal ventaja de SDSL con respecto a HDSL es...",
    options: [
      "A. Mayor velocidad de transmisión.",
      "B. Gran cantidad de implementaciones propietarias.",
      "C. Utilización de menor número de repetidores.",
      "D. Utilización de un único bucle de abonado y mantenimiento de la señal de voz analógica.",
    ],
    correctAnswer: "d",
  },
  {
    id: "redes_recop_q37",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-12",
    type: "mc",
    points: 1,
    question: "VDSL ha sido diseñada para trabajar con...",
    options: ["A. IP", "B. Ethernet", "C. Token Ring", "D. ATM"],
    correctAnswer: "d",
  },
  {
    id: "redes_recop_q38",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-12",
    type: "mc",
    points: 1,
    question:
      "¿Cuál es la capacidad teórica de un nodo primario en una red HFC?",
    options: ["A. 40000 HP", "B. 10000 HP", "C. 2000 HP", "D. 500 HP"],
    correctAnswer: "a",
  },
  {
    id: "redes_recop_q39",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-12",
    type: "mc",
    points: 1,
    question:
      "¿Cuál de los siguientes Estándares de Servicios de Datos sobre Redes de Cable es más eficiente para la utilización de IP?",
    options: [
      "A. IEEE 802.14",
      "B. DOCSIS",
      "C. DAVIC/DVB",
      "D. Ninguno de los anteriores",
    ],
    correctAnswer: "b",
  },
  {
    id: "redes_recop_q40",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-12",
    type: "mc",
    points: 1,
    question:
      "¿Cuál de los siguientes Estándares de Servicios de Datos sobre Redes de Cable puede no usar ATM?",
    options: [
      "A. IEEE 802.14",
      "B. DOCSIS",
      "C. DAVIC/DVB",
      "D. Ninguno de los anteriores",
    ],
    correctAnswer: "b",
  },
  {
    id: "redes_recop_q41",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-12",
    type: "mc",
    points: 1,
    question:
      "Las redes de cable HFC integran servicios IP mediante la utilización de un protocolo MAC en el...",
    options: [
      "A. Canal ascendente (usuario a red).",
      "B. Canal descendente (red a usuario).",
      "C. Canal ascendente y descendente.",
      "D. Estas redes no utilizan ningún tipo de protocolo MAC.",
    ],
    correctAnswer: "a",
  },
  {
    id: "redes_recop_q42",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-12",
    type: "mc",
    points: 1,
    question: "¿Cuál de las siguientes afirmaciones NO es válida para ATM?",
    options: [
      "A. Tamaño de paquete fijo.",
      "B. Control de errores sobre el campo cabecera de los paquetes.",
      "C. Control de errores sobre el campo de datos del paquete.",
      "D. Mínimo control de flujo.",
    ],
    correctAnswer: "c",
  },
  {
    id: "redes_recop_q43",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-12",
    type: "mc",
    points: 1,
    question:
      "En ATM, la agrupación de canales lógicos (VCC) en caminos lógicos (VPC)...",
    options: [
      "A. Complica las labores de los nodos intermedios.",
      "B. Aumenta el coste de control.",
      "C. Aumenta el número de canales que pueden ser multiplexados sobre un medio físico.",
      "D. Facilita las labores de encaminamiento de los nodos intermedios.",
    ],
    correctAnswer: "d",
  },
  {
    id: "redes_recop_q44",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-12",
    type: "mc",
    points: 1,
    question: "ATM gestiona el canal de transmisión...",
    options: [
      "A. De forma estática.",
      "B. De forma dinámica con priorización de tráfico.",
      "C. De forma dinámica sin priorización de tráfico.",
      "D. No es posible gestionar el canal de transmisión en ATM.",
    ],
    correctAnswer: "c",
  },
  {
    id: "redes_recop_q45",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-12",
    type: "mc",
    points: 1,
    question:
      "La clase 4 de la capa de adaptación ATM se define para tráfico en el cual...",
    options: [
      "A. Existe una relación de tiempo entre fuente y destino, la tasa de bits es constante y el servicio es orientado a conexión.",
      "B. No existe una relación de tiempo entre fuente y destino, la tasa de bits es constante y el servicio es orientado a conexión.",
      "C. Existe una relación de tiempo entre fuente y destino, la tasa de bits es constante y el servicio es no orientado a conexión.",
      "D. No existe una relación de tiempo entre fuente y destino, la tasa de bits es constante y el servicio es no orientado a conexión.",
    ],
    correctAnswer: "d",
  },
  {
    id: "redes_recop_q46",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-12",
    type: "mc",
    points: 1,
    question:
      "En Emulación de LAN ATM, el LECS (LAN Emulation Configuration Server) se encarga de...",
    options: [
      "A. Mantener una base de datos con las correspondencias entre direcciones MAC y direcciones ATM.",
      "B. Establecer circuitos físicos con todos los LEC de una determinada ELAN.",
      "C. Indicar a los clientes de ELAN dónde se encuentra su correspondiente servidor.",
      "D. Convertir direcciones ATM en direcciones IP.",
    ],
    correctAnswer: "c",
  },
  {
    id: "redes_recop_q47",
    exam: "daypo-recopilatorio-lara",
    topic: "tema-12",
    type: "mc",
    points: 1,
    question:
      "En emulación LAN ATM, el procedimiento ILMI (Interim Local Management Interface) se utiliza...",
    options: [
      "A. Para localizar a un LEC (LAN Emulation Client).",
      "B. Para localizar a un LECS (LAN Emulation Configuration Server).",
      "C. Para localizar a un LES (LAN Emulation Server).",
      "D. Para localizar a un BUS (Broadcast and Unknown Server).",
    ],
    correctAnswer: "b",
  },
];
