name: 🔎 Indexación en motores de búsqueda

on:
  workflow_dispatch:

jobs:
  indexnow:
    name: 🔎 Bing IndexNow
    if: github.repository == 'TeenBiscuits/Pasame-Examenes'
    runs-on: ubuntu-latest
    steps:
      - name: ⬆️ Subir Sitemap
        uses: bojieyang/indexnow-action@v3.0.0
        with:
          sitemap-location: "https://pe.pablopl.dev/sitemap.xml"
          key: ${{ secrets.INDEXNOW_KEY }}
          endpoint: www.bing.com
          failure-strategy: error

  google-indexing:
    name: 🔎 Google Index
    if: github.repository == 'TeenBiscuits/Pasame-Examenes'
    runs-on: ubuntu-latest
    steps:
      - name: ⬆️ Subir Urls
        uses: robingenz/action-google-indexing@v1.0.2
        with:
          siteUrl: "pe.pablopl.dev"
          gcpServiceAccountKey: ${{ secrets.GCP_SA_KEY }}
